### ISSUE TITLE
Low RandomX hashrate on systems with more than 64 threads

### ISSUE THREAD

**Issue by Zorg33** [doktor83/SRBMiner-Multi#10]
I tested the Windows miner on my 4x Xeon CPU servers and found that on 2 node servers it's working fine, but on 4 node servers (with more than 64 threads) the hashrate is very low (about 60% of xmrig hashrate) althought the cpu thread affinity gets set correctly!

**Update**: I did a test on my other 4 CPU server with only 32 threads and the hashrate is OK there!
So it seems the issue is only dependent on the number of threads and not the number of nodes.

My assumption is that the problem occurs also on 1 CPU systems that has more than 64 threads. But I can't test that.

I guess it's related to the affinity management of Windows.
According to MS documentation you have CPU Groups (group = NUMA node, afaik) and you have a 64 bit bitmask in each group. So managing 64+ threads can be tricky. Also there could be a problem in your code where you are only using 64 bit bitmasks?

**Comment by doktor83** [comment]
Fixed in 0.4.7!
Thanks!
