### ISSUE TITLE
[BUG] MSR tweaking disabled when running LibreHardwareMonitor

### ISSUE THREAD

**Issue by RainbowMiner** [doktor83/SRBMiner-Multi#100]
It's a Windows problem:
If LibreHardwareMonitor (or via librehardwaremonitorlib.dll + some c# code) runs, it creates and loads the kernel driver WinRing0_1_2_0 with it's own different service name. This seems to block SrbminerMulti from applying MSR tweaking. The Xmrig miner seems to detect and reuse the kernel driver with different service name properly, even though it warns, that it has a different service name than WinRing0_1_2_0.
This Xmrig commit to implement the detection can be found here: https://github.com/xmrig/xmrig/commit/f682d9a2e99a98a5aa40a72ff3c6e4085f4dd23d

Would you please add something similar, so that SrbminerMulti reuses the WinRing0_1_2_0 kernel driver, even if it has a different service name?

**Comment by GhostWriter85** [comment]
Hello... Can someone let me know how I became part of this SRBminermulti? I gain no money/mining/shares/etc...

**Comment by RainbowMiner** [comment]
@doktor83 have you already had the time to look into this problem?

**Comment by doktor83** [comment]
Honestly, when i get time to work on the miner im looking at more important stuff.. This is really low priority..

**Comment by doktor83** [comment]
should be fixed in 0.9.4
