### ISSUE TITLE
From Russia, when communicating with American pools, a lot of rejected decisions

### ISSUE THREAD

**Issue by BARUCHER777** [doktor83/SRBMiner-Multi#101]
Win 10 Corp LTSC 64-bit (CPU AMD - 5800X)
Too many rejected when mining on us-east.deepfields.io:4234!eu.letshash.it:5966
![dupl_shares](https://user-images.githubusercontent.com/18327150/154202372-7065a4e8-d443-4beb-b45d-33443ec34ff9.jpg)

**Comment by Xarthie** [comment]
This issue is more prominent if the latency is lower.. about 75% of my shares are rejected. About 50% are rejected if the latency is higher:
![rejected_shares](https://user-images.githubusercontent.com/97554091/154257860-00188b12-7dcd-4b5c-acc5-7e09e1608e71.png)

**Comment by doktor83** [comment]
Please next time read announcement first.
