### ISSUE TITLE
Dual Socket EPYC 128 threads Processor, only 1 SOCKET cpu is used instead of both.

### ISSUE THREAD

**Issue by clearchrome999** [doktor83/SRBMiner-Multi#102]
SRBMiner-MULTI 0.9.2

When using EPYC 7742 (ENG SAMPLE) dual socket CPUs, 64 Cores are detected correctly on each (ok) and mining with 128 cores total according to  (ok,) but Win10 taskmanager indicating 50% CPU usage, meaning only 1 CPU socket is used.
Tried to run with Admin, and different cpu-intensity, same thing.  
Tried using JAYDEE miner, works at 100% usage.  

SBMINER logs below;

CPU0 : AMD Eng Sample: 100-000000053-04_32/20_N [L3:  16384 KB][L2: 32768 KB][L1: 2048 KB][PU:  64]
CPU1 : AMD Eng Sample: 100-000000053-04_32/20_N [L3:  16384 KB][L2: 32768 KB][L1: 2048 KB][PU:  64]

===================================================================
Algorithm/s         : curvehash [0.85% fee]
Gpu mining          : disabled
Cpu mining          : enabled
Watchdog            : enabled
Huge-pages          : available
HW-Aes              : available

[2022-03-01 13:36:09] Run miner as administrator to enable MSR tweaks
[2022-03-01 13:36:09] Algorithm 0 available values for --cpu-threads-intensity : 1, 2
[2022-03-01 13:36:14] 128 CPU core/s - 128 thread/s detected
[2022-03-01 13:36:14] Using 126 thread/s for CPU mining
[2022-03-01 13:36:15] SSL/TLS connection established with stratum-na.rplant.xyz:17030 [ECDHE-RSA-AES128-GCM-SHA256]
[2022-03-01 13:36:16] Connected to stratum-na.rplant.xyz:17030 [curvehash]

**Comment by doktor83** [comment]
Did you set --cpu-threads 126 ?

**Comment by doktor83** [comment]
Ok so if you dont set the number of threads manually, does it work ok ?

**Comment by clearchrome999** [comment]
> Ok so if you dont set the number of threads manually, does it work ok ?

Yep, just tried and working...thats weird.

**Comment by lowbrass** [comment]
I'm jealous of the OP as I have but a single-socket 7742 Eng Sample. However, I found myself having a similar issue when I first started mining with it. Same thing: 64 threads showed 100% utilization, 128 threads showed 50%. (Huh?) I switched to Linux, thinking it'd be different, but issue remained. 

I searched someone's issues archive - it may have been xmrig - where a dual socket system owner lamented its relatively poor performance. Something called NPS was brought up. When I looked into what that meant, it made me aware of a parameter in SRBMiner called "**--disable-numa**". Even though I'm single-socket, adding this parameter to my config was what gave me the desired behavior of 128 threads at 100%. Works the same under Linux and Windows. 

Diagnosis was aided by the fact I have my EPYC's power supply plugged into a Watt meter. The power draw and hashing performance was noticeably increased when I added --disable-numa. Mining curvehash @128 threads was a constant 275-280W prior to 0.93; Now, 0.93+ is even more efficient, where I get the same hashing performance, but at 245-ish W.

**Comment by kaka1365** [comment]
Okay

**Comment by clearchrome999** [comment]
> > > Ok so if you dont set the number of threads manually, does it work ok ?
> > 
> > 
> > Yep, just tried and working...thats weird.
> 
> Now try this: **--cpu-threads 126 --cpu-affinity -3**

Yes, that does it!   thank you so much!    im not sure why -3 for CPU affinity...
