### ISSUE TITLE
Hashrate spikes

### ISSUE THREAD

**Issue by aliyazdi75** [doktor83/SRBMiner-Multi#103]
Hi, sometimes I have some spikes like the image below like from 63 to something like 85 and the real hashrate is 63. Is it an issue?

![image](https://user-images.githubusercontent.com/20153831/156405625-5217155f-1771-48dc-9e39-de448fec1e50.png)

**Comment by doktor83** [comment]
if you have the average hashrate on poolside too i would say it's not an issue

**Comment by aliyazdi75** [comment]
No there are no spikes on the poolside.
Sorry, I have another question, I have like 96% efficiency (860A - 40R) is this normal? How can I decrease stales? I don't have many rejects using other miners.

![image](https://user-images.githubusercontent.com/20153831/156517076-1e61c231-974b-4acc-9b18-2e3dc40a0ed0.png)
