### ISSUE TITLE
add support for sha3d (bsha3) algorithm

### ISSUE THREAD

**Issue by JayBitron** [doktor83/SRBMiner-Multi#107]
Hello, please add support for the sha3d (bsha3) algorithm, thanks!

**Comment by doktor83** [comment]
Ok, its an easy one. Next release will support it.

**Comment by JayBitron** [comment]
Thank you so much! Kylacoin is also using the same algorithm https://miningpoolstats.stream/kylacoin

**Comment by JayBitron** [comment]
Hello, any update?

**Comment by doktor83** [comment]
in a day or two

**Comment by doktor83** [comment]
added in 0.9.4
