### ISSUE TITLE
This software does not work on ANY Linux CentOS 7 with glibc 2.17 ..

### ISSUE THREAD

**Issue by FullyElectric** [doktor83/SRBMiner-Multi#109]
This software does not work on ANY Linux CentOS 7 with glibc 2.17 .. please fix or compile a static build please

**Comment by doktor83** [comment]
no, update your OS from 2012. It's 10 years for god's sake.

**Comment by FullyElectric** [comment]
We are running the latest version of CentOS 7 .. release just last year and
2.18 is also like 10 years ago .. the latest version of CentOS 7 uses glib
2.17 and your resent update is looking for 2.18.. that is just as old as
2.17 .. plus it’s easy to just support whatever people like to run but also
compiling a static version ..
