### ISSUE TITLE
File SRBMiner-Multi-0-6-0-win64.zip

### ISSUE THREAD

**Issue by kftoom** [doktor83/SRBMiner-Multi#11]
Hi is the file SRBMiner-Multi-0-6-0-win64.zip compatible with Windows 8?

**Comment by doktor83** [comment]
What do you mean? It's an archive, you need to unzip it by using winzip or similar application.

**Comment by kftoom** [comment]
Yes I have unzipped the folder and in the new one only 5 files come up.
It doesn't look like on the video showing how to mine Wow coins. I'm stuck here.

**Comment by doktor83** [comment]
Wow coins , you mean Wownero ?

`SRBMiner-MULTI.exe --disable-gpu --algorithm randomwow --pool wownero.herominers.com:10660 --wallet your-wownero-wallet`

**Comment by kftoom** [comment]
Yes I followed the instructions on the video. They did not unzip the folder. Instead they made a copy and paste of the file called start-mining-conceal. My computer does not allow me to do the copy and paste.

**Comment by kftoom** [comment]
This is the video https://www.youtube.com/watch?v=whVuL1uE7UY&feature=emb_logo

**Comment by doktor83** [comment]
This video really shows you every step you need to do so you can mine Wow. For support you can come to the discord channel [https://discord.gg/zXY23De](https://discord.gg/zXY23De)
