### ISSUE TITLE
yescryptr16 performs poorly on Ryzen processors

### ISSUE THREAD

**Issue by mshnryman** [doktor83/SRBMiner-Multi#111]
Tested on 5950x & TR 3970x

5950x gets best hash when using 11 threads, default with 32 threads is less than half of the hashrate
3970 gets best hash when using 25 threads, default with 64 threads is also less than half

**Comment by doktor83** [comment]
when you say performs poorly that means poorly compared to which miner?

**Comment by mshnryman** [comment]
cpuminer - this algo isn't really optimized very well for zen anyway, but does better on cpu

**Comment by doktor83** [comment]
there are a lot of forks of cpuminer, which one?
Also can you tell me hashrates for both miner (cpuminer, srb) - with same number of threads?
Im curious how much is the difference. Because none of the open source cpuminer forks i know of performs better..

**Comment by papadrams** [comment]
Thats my results on 5600g (6 cores, 12 threads)
Srb by default uses 8 threads, cpuminer rplant (next best for me) uses by default 6 threads

Overclocked Ryzen 5 5600G
		
Threads	SRB	Rplant
   12	        975	971
   11	        983	956
   10	      1003	972
    9	      1014	960
    8	      1017	995
    7	      1007	955
    6	        978	998

**Comment by papadrams** [comment]
I'm sorry, i am not the creator of this issue. I just shared my stats cause he was talking about ryzen.
