### ISSUE TITLE
Cannot mine 4 crypto at same time

### ISSUE THREAD

**Issue by karkarkuss** [doktor83/SRBMiner-Multi#112]
Hey.
I want to mine 4 crypto at same time, but it allows me to mine only 3...

my code

setx GPU_MAX_HEAP_SIZE 100
setx GPU_MAX_USE_SYNC_OBJECTS 1
setx GPU_SINGLE_ALLOC_PERCENT 100
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_MAX_SINGLE_ALLOC_PERCENT 100
u/echo off
cd %~dp0
cls
SRBMiner-MULTI.exe --disable-cpu --algorithm autolykos2;blake3_alephium;kawpow;randomkeva --pool de.ergo.herominers.com:1180;de.alephium.herominers.com:1199;de.ravencoin.herominers.com:1140!rvn-eu1.nanopool.org:12222;de.kevacoin.herominers.com:1163 --wallet 9i4V4z9V37aWxgdK5dhv521UbSsahuo5nz2PkFKCktrLrPQxEKD.MartinsPC1;14PFz4DGwSBatYjHmEecL542YQckhYj17uBvVnnKkniFJ.MartinsPC1;RFgUERPZ8zrzgRc2VRJcG6UCgZXaeYEpzo.MartinsPC1;VEodtLJs1Bqz6n6WarmpQXFPHGvUDcfnGF.MartinsPC1 --gpu-boost 3
pause

https://ibb.co/S6vDCBp - image

and to enable cpu minning i just need edit this line disable-cpu to enable-cpu?

**Comment by karkarkuss** [comment]
when i change code to enable-cpu, it says press any key to continue and just exit...

https://ibb.co/px3qgjj

**Comment by karkarkuss** [comment]
maybe you can help me with code? i want to mine all 4 crypto, with gpu and cpu.

**Comment by doktor83** [comment]
you should use separate instances for CPU and GPU mining, from those 4 algorithms only randomkeva is a CPU algorithm, the other ones dont make sense CPU mining. Also miner dies probably because not enough RAM for kawpow DAG , autolykos2 dataset or something third.

**Comment by karkarkuss** [comment]
> 

So if i add more gpu, then everything should be ok?
