### ISSUE TITLE
Error in config.txt (ParseError) Got some trouble in parsing configuration/s

### ISSUE THREAD

**Issue by sirdapa** [doktor83/SRBMiner-Multi#113]
I want to run srb direct using config.txt without .bat / .cmd file. but how to generate that ? I try use parrameter --setup. but output file keep .bat

**Comment by doktor83** [comment]
config file is deprecated, i mean some basic stuff might still work i haven't removed support for configuration file but its not maintained/updated for a long time now. And it won't be.
