### ISSUE TITLE
kaspa mining problem

### ISSUE THREAD

**Issue by altinsoft** [doktor83/SRBMiner-Multi#114]
![resim](https://user-images.githubusercontent.com/31034706/173236480-da3c9e16-5da1-4577-9d73-ac706d046efd.png)

Some cards are not mining. This a bug.

**Comment by doktor83** [comment]
Yes it is, it's a Hiveos and mixed drivers bug.

**Comment by doktor83** [comment]
Tip : try latest release ( 0.9.6 ) it might resolve this issue
