### ISSUE TITLE
Sapphire HD7970 GHZ Edition Vapour-x is discovered OK, but only 3GB - not the full 6.

### ISSUE THREAD

**Issue by EeTheG** [doktor83/SRBMiner-Multi#12]
I know, I am sad using radiators for mining - I can't help it. Trying SRB Miner Multi and this flags at the start:

GPU0 : amd_readeon_hd_7900_series   [tahiti   ][MEM : **3072 MB**][CU: 32][BUS: 01]

Should be **6144** - seems to be a fairly common oversight? Any chance this could be fixed? My house is cold and I need the heat!!

Cheers.

**Comment by doktor83** [comment]
That value is what video driver reports, nothing i can do about it. Also it shouldn't be an issue when you are mining, just find the right intensity for the algorithm you want to mine.
