### ISSUE TITLE
Kaspa socket error 104 

### ISSUE THREAD

**Issue by Papiitoo** [doktor83/SRBMiner-Multi#121]
Hi!

I installed kaspad full node on a desktop computer. I waited for full synchronization, then I tried to mine my own node on the local network. (server ip 192.168.10.100) The miner connects to the node, but after a few seconds the error message "socket error 104" appears. Then it connects again, but again "socket error 104". I tried server url: "node+tcp://192.168.10.100: 16110" , "solo+tcp://192.168.10.100:16110", "http://192.168.10.100:16110" , "192.168.10.100:16110 " Always socket error 104

**Comment by doktor83** [comment]
Solo not supported, only pool (stratum)

**Comment by Papiitoo** [comment]
Thanks for you reply
