### ISSUE TITLE
nicehash bug

### ISSUE THREAD

**Issue by farhadcrazysv** [doktor83/SRBMiner-Multi#122]
when i mine dual eth + kaspa . when i  use nicehash as eth pool the srbminer  ( leatest version) will stop mining and this msg came up : worker thread stopped   after 15-25 mins and after 10mins its start again . but with other pools i dont have this problem . plz fix this bug than
![Untitled](https://user-images.githubusercontent.com/58301393/178990090-5784a410-3967-4e6c-9c67-a5ac5c8ecd11.jpg)
x

**Comment by doktor83** [comment]
try latest release https://github.com/doktor83/SRBMiner-Multi/releases/tag/1.0.2
