### ISSUE TITLE
RX 580 mining on ethereum pools does not start.

### ISSUE THREAD

**Issue by DJLazerjet** [doktor83/SRBMiner-Multi#124]
Hello. Mining on Ethereum pools does not start on Windows 10 on versions 0.9.9 - 1.0.2. I receive this empty window..

![изображение](https://user-images.githubusercontent.com/46873002/179398011-a0b70329-8cd3-4ee4-9159-d227a1f5306f.png)

**Comment by DJLazerjet** [comment]
When i wanna start dual mining ETH+KASPA... miner writes the same.

**Comment by doktor83** [comment]
> When i wanna start dual mining ETH+KASPA... miner writes the same. GPU RX 580 8GB, driver 20.10.1. Location - Russia. Some guys says miner not working because RosComNadzor blocks the port of ETH MEV on your miner. I tried to connect via VPN, but nothing happend..

Exactly, if you are from Russia ethermine (where the devfee is mined) is blocked. I made some workarounds and now connections for Ethash go through my socks5 proxy, so you should be ok now? Can you test ?
