### ISSUE TITLE
Disabled gpu still uses dual mining algorith.

### ISSUE THREAD

**Issue by vilemooni** [doktor83/SRBMiner-Multi#125]
Disabled gpu still uses dual mining algorith.

Hi, disabling gpu for mining disables the main algorithm from mining but srb will still try to mine the second algorith on said gpu. In my excamle i tried ETH+KASPA.

**Comment by doktor83** [comment]
Tried **--gpu-id 0!2!3!4!5;0!2!3!4!5** to disable gpu1 ?

**Comment by vilemooni** [comment]
Yes this is how i managed to disable the eth mining on the card. My idea was to use srbminer for my 4 polaris cards and trm for 2 of my vegas as i wasn't able to hit 50MH/s with SRBminer. I set up the miners with device limitations correctly but SRB would still try to mine kaspa with vegas and ofc trm wouldn't like this.

**Comment by doktor83** [comment]
I tested it and it does not use the gpu which isnt specified in --gpu-id. So you probably set up your sheet on hiveos wrong.
