### ISSUE TITLE
Support for VKAX - MIKE mining algorithm - CPU mining coin

### ISSUE THREAD

**Issue by blackmennewstyle** [doktor83/SRBMiner-Multi#126]
Hello,

Could you consider to add support for VKAX coin, which is a CPU mining coin using the MIKE mining algorithm. Apparently it's a fork of GHOSTRIDER mining algorithm used by RTM.

**Comment by doktor83** [comment]
Added [https://github.com/doktor83/SRBMiner-Multi/releases/tag/1.0.3](url)
