### ISSUE TITLE
0.9.4 Card Support --> Newer Releases

### ISSUE THREAD

**Issue by iamhumanipromise** [doktor83/SRBMiner-Multi#127]
Hello there! I am having issues with another miner with older radeon cards. All the modprobe.d configs are in place, drivers are correct -- but the cards only work in SRBMiner, which is cool! I found a miner! 

That being said - are you in the US or Canada for me to send a GCN 1 and GCN 2 card for testing? Or can I provide you access to a computer here for testing/tweaking for GCN 1/ GCN 2 / GCN 3 support? 

(An R9 290 unmodified gets about 15MH/s stock on RVN which is not bad. I'm sure with tweaks this could easily get to 22MH/s+, etc) -- these cards are all about to become SUPER cheap but still mine...

**Comment by doktor83** [comment]
Hi there, i'll have to dissapoint you but i won't be adding back support for those old cards, sorry.

**Comment by iamhumanipromise** [comment]
Ah it seemed as if the reason was due to not owning the cards for testing.

How can I give you access to a machine for testing.
