### ISSUE TITLE
disable auto tune for dual mining didnt work 

### ISSUE THREAD

**Issue by farhadcrazysv** [doktor83/SRBMiner-Multi#129]
hey how r u guys . i want to set the intensity for my dual mining eth+kaspa and --gpu-auto-tune 0 is not working and auto tune choose intensity so high and i loose hashrate on eth . plz in next version put somthing that we can disable auto tune for dual mining 
thanx alot 
regards

**Comment by doktor83** [comment]
if you manually set the intensities then auto tune wont be activated. Like --gpu-intensity 24;2

**Comment by farhadcrazysv** [comment]
At the beginning of starting up its written the intensity set , but after that auto tune set it again unfortunately;(

**Comment by doktor83** [comment]
show me you config

**Comment by farhadcrazysv** [comment]
--disable-cpu --algorithm ethash --algorithm kaspa --pool stratum+ssl://eu1.ethermine.org:5555 --pool ru.acc-pool.pw:16061!hk.acc-pool.pw:16061!ca.acc-pool.pw:16061!acc-pool.pw:16061 --wallet 0x333E36A16Fa3d82850612fD624C484D25196D556.3F --wallet kaspa:qz2zgf0munwnpy3sjphrqdku9k6nlh7ph02l9uez2az8e97d6s98yazfsw80p.3F --api-enable --gpu-auto-tune 0 --gpu-intensity 0;7 --password x --watchdog-script=reboot.sh

**Comment by doktor83** [comment]
well first, there is no **--gpu-auto-tune 0**, so that ain't doing nothing. Second, i told you to manually set intensity ( example was --gpu-intensity 24;2 ), but you didn't do that. You set **--gpu-intensity 0;7**, meaning auto set intensity for first algorithm, that's why auto tune runs.
