### ISSUE TITLE
Argon2d_16000 over hashrate

### ISSUE THREAD

**Issue by Quake4** [doktor83/SRBMiner-Multi#130]
in the program window on rx580 shows 4.7 kh, but on the pool side 1.2-1.4 kh

**Comment by doktor83** [comment]
im pretty sure if this was the case for everyone then it would be already reported cause that algo exists in miner for a long time.

**Comment by doktor83** [comment]
![Untitled](https://user-images.githubusercontent.com/6808360/185548110-babacd18-58f2-4e0e-bfdb-711eb03e5886.jpg)

i ran a test for you, you can see the result yourself.

**Comment by Quake4** [comment]
![image](https://user-images.githubusercontent.com/29517243/185584484-cf4e065f-91e8-4420-8514-9e064f4a1037.png)

**Comment by Quake4** [comment]
there are too few shares at such a speed and diff of 0.5

**Comment by Quake4** [comment]
![image](https://user-images.githubusercontent.com/29517243/185586871-9144bcbd-d274-4a19-9cc2-6109d08892ec.png)

**Comment by Quake4** [comment]
![image](https://user-images.githubusercontent.com/29517243/185587423-5e15418a-7f12-432a-b221-fa6a6ac1c1d3.png)

**Comment by doktor83** [comment]
which gpu driver version is that?

**Comment by doktor83** [comment]
Ok i took the time (i dont know why, when i know there is no issue) and did a test :
Rx580 8g , amd driver 22.7.1, SRB version 1.0.5

![Untitled](https://user-images.githubusercontent.com/6808360/185734190-e6d9cc61-70da-458f-8ec7-b3509444a7b8.jpg)

As far as im concerned there is no issue with the miner showing bad/fake hashrate.

**Comment by Quake4** [comment]
![rx580](https://user-images.githubusercontent.com/29517243/185743551-32885781-660e-4e5c-b250-0162ea36801b.png)

**Comment by Quake4** [comment]
rx580 4G

**Comment by doktor83** [comment]
yes i can see, i tested on 2 gpu's you can also see no issue there. Have you tested on other GPU's too, not only that one ? Asked any of your users do they have the same issue as you ? Have you tried updating video driver ?
