### ISSUE TITLE
Ubuntu 20.04.2 - AMDGPU 21.50.2 - Radeon VII - SRBMiner-Multi-1-0-6 - No worker devices found

### ISSUE THREAD

**Issue by blackmennewstyle** [doktor83/SRBMiner-Multi#133]
Hello,

I'm trying to mine on **Ubuntu 20.04.2** using the **AMDGPU 21.50.2** drivers with my **Radeon VII** but i'm getting a weird message.

When i run `sudo /home/ceedii/SRBMiner-Multi-1-0-6/SRBMiner-MULTI --list-devices`
```
Detected GPU devices

GPU0  [1][0] [03:00.0] : amd_radeon_vii [gfx906:sramecc+:xnack-] [16368 MB] [CU: 60] [MaxB: 13912 MB] [MID: 1][CID: 1]

```
My GPU is detected right?

However when i run the following command `sudo /home/ceedii/SRBMiner-Multi-1-0-6/SRBMiner-MULTI --api-enable --api-port 4454 --api-rig-name epimetheus --algorithm cryptonight_gpu --pool stratum+ssl://sg.conceal.herominers.com:1115 --wallet ccxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx --gpu-id GPU0 --enable-workers-ramp-up --gpu-auto-tune 1 --disable-cpu --password epimetheus --extended-log`
```
Detecting OpenCL devices...

GPU0 : amd_radeon_vii                        [gfx906       ][MEM: 16368 MB][CU: 60][BUS: 03]

======================================================================
SRBMiner-MULTI 1.0.6

Press 's' to display stats
Press 'h' to display hashrate
Press 'p' to switch to the next pool
Press 'o' to switch to the previous pool
Press 0-9 to disable/enable GPU 0-9, shift+0-9 for GPU 10-19
Press + or - to change gpu boost value
======================================================================

Algorithm/s         : cryptonight_gpu [0.85% fee]
Gpu mining          : enabled
Cpu mining          : disabled
Watchdog            : enabled
Gpu tweaking        : enabled

[2022-09-01 14:35:30] No worker devices found

```
Please, can you tell me what am i doing wrong?

**Comment by doktor83** [comment]
**--gpu-id GPU0** is wrong, it should be --gpu-id 0

**Comment by blackmennewstyle** [comment]
> **--gpu-id GPU0** is wrong, it should be --gpu-id 0

Really? I was mining with an older driver AMDGPU 20.40 with a RX 570 4B and using `GPU0` actually worked.

OK, I tried that as well and i got the exact same error `No worker devices found`.

Could it be because AMDGPU 20.40 uses OPENCL PAL,LEGACY and AMDGPU 21.50.2 uses OPENCL ROCR,LEGACY?
ROCR is a derivative of ROCM, used by AMD in its latest proprietary drivers.

**Comment by doktor83** [comment]
Yes, driver could be an issue, im using PAL format for Vega binaries, only a few algorithms have ROCM binaries too. Try 20.40 and report back

**Comment by blackmennewstyle** [comment]
> Yes, driver could be an issue, im using PAL format for Vega binaries, only a few algorithms have ROCM binaries too. Try 20.40 and report back

Sorry for the late reply but i can confirm it works properly when using old drivers like AMDGPU 20.40 which have OPENCL PAL,LEGACY.

I think you should consider to start supporting newer drivers OPENCL ROCR (ROCM),LEGACY because moving forward NAVI1, 2, 3 and next generations of GPU will be build on these OPENCL librairies and they come with important fixes and optimizations.

Happy midweek and keep it up the great job <3

**Comment by doktor83** [comment]
Only Vega's have this PAL/ROCM thing depending from driver version. Polaris is legacy, works on all drivers, and of course RDNA is already ROCM, so no issues there. So to summarize, some algorithms already have both PAL/ROCM support in miner for Vegas, those are let's call em the profitable ones. Algos like cryptonight_gpu don't have ROCM support. Adding support for every algo would just make the miner binary size grow, and probably nobody would use 90% of those algorithms.

**Comment by blackmennewstyle** [comment]
I tried to use an older of SRBMiner-Multi with the latest AMDGPU drivers and i got a complete different error:

```
sudo /home/ceedii/SRBMiner-Multi-0-9-4/SRBMiner-MULTI --api-enable --api-port 4454 --api-rig-name epimetheus --algorithm cryptonight_gpu --pool stratum+ssl://sg.conceal.herominers.com:1115 --wallet ccxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx --gpu-id GPU0 --enable-workers-ramp-up --gpu-auto-tune 1 --disable-cpu --password epimetheus --extended-log 
Detecting OpenCL devices...

GPU0 : amd_radeon_vii                        [gfx906       ][MEM: 16368 MB][CU: 60][BUS: 03]

======================================================================
SRBMiner-MULTI 0.9.4

Press 's' to display stats
Press 'h' to display hashrate
Press 'p' to switch to the next pool
Press 'o' to switch to the previous pool
Press 0-9 to disable/enable GPU 0-9, shift+0-9 for GPU 10-19
Press + or - to change gpu boost value
======================================================================

Algorithm/s         : cryptonight_gpu [0.85% fee]
Gpu mining          : enabled
Cpu mining          : disabled
Watchdog            : enabled
Gpu tweaking        : enabled

[2022-09-07 14:14:23] Auto tune can run for a long time, please be patient
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)
```

This is so weird to be honest.
