### ISSUE TITLE
--proxy option ISSUE

### ISSUE THREAD

**Issue by ssminiGG** [doktor83/SRBMiner-Multi#137]
--proxy ip:port (working ok)
--proxy user:pass@ip:port (ERROR: double free or corruption (out))

Thanks for read.

**Comment by doktor83** [comment]
works for me. os ?

**Comment by ssminiGG** [comment]
> works for me. os ?

Ubuntu 20.04 br
Thank you very much

**Comment by ssminiGG** [comment]
> works for me. os ?
I found the problem
It seems srbminer doesn't support socks5h (only socks5). So the function is completely useless when the domain is locked.

**Comment by doktor83** [comment]
socks5h should mean the hostname is resolved to ip at the proxy side, which actually is the case in SRBMiner (host isnt resolved locally on the machine it's running on).

**Comment by ssminiGG** [comment]
Thank you for replying to me
I'm really sorry for this. The username of the proxy is wrong. Everything is ok now.
One more time thank you very much.
