### ISSUE TITLE
Kaspa Mining 

### ISSUE THREAD

**Issue by bettaxtorn00** [doktor83/SRBMiner-Multi#139]
Hi, I was wondering if there is any problem with kaspa solo mining. In practice I noticed that after a while the counter of accepted shares resets and sometimes the cards stop mining.
I have 2 amd gpus (6600xt and 6800xt) on hiveos system. Thank you

**Comment by doktor83** [comment]
SRBMiner doesn't support solo mining, only pool. So its not clear what you mean.

**Comment by bettaxtorn00** [comment]
I'm sorry I didn't mean solo mining but only mining kaspa coin.

**Comment by DeeDeeRanged** [comment]
Here is a screenshot of SRBMiner doing only kaspa in hiveos
https://bitcointalk.org/index.php?topic=4724735.msg60966221#msg60966221

**Comment by doktor83** [comment]
> Hi, I was wondering if there is any problem with kaspa solo mining. In practice I noticed that after a while the counter of accepted shares resets and sometimes the cards stop mining. I have 2 amd gpus (6600xt and 6800xt) on hiveos system. Thank you

i can't know what is happening without some logs, but if i need to guess it would be that your gpu crashes and miner restarts itself.
