### ISSUE TITLE
Algorithm addition 

### ISSUE THREAD

**Issue by imrecsoka** [doktor83/SRBMiner-Multi#14]
Hi, would you be able to add m7m algorithm, thanks

**Comment by doktor83** [comment]
It was added earlier but then i recently removed it. You can try an earlier version which supports it.

**Comment by imrecsoka** [comment]
Oh okay m thank you i will have a look at that.
It seems to be popular again 2 types of CPU coins using this algorithm, maybe worth while reinstating it ?
