### ISSUE TITLE
Gpu mine verus

### ISSUE THREAD

**Issue by tonybeesknees** [doktor83/SRBMiner-Multi#141]
I have a rig with rx570 8gb cards 
I can not get gpu mining working on verus coin 
The hash rate shows for each card 
But it does not mine

**Comment by doktor83** [comment]
if it shows hashrate and finds shares then it's mining?

**Comment by tonybeesknees** [comment]
It shows hash rate but dose not even seam to get jobs to submit shares 
A cpu at 5kh  works 
Cards to 50 kh run for a hour and nothing

**Comment by tonybeesknees** [comment]
Sorry it is recieving jobs 
Just never seams to send any

**Comment by tonybeesknees** [comment]
![Uploading 16642593507905101111987535239650.jpg…]()

**Comment by doktor83** [comment]
can you send me a log? add --log-file verus-log.txt --extended-log and leave it running for 3-4-5 minutes then upload the log somewhere and link it here

**Comment by tonybeesknees** [comment]
I am using hiveos 
Where would i find the log

**Comment by tonybeesknees** [comment]
i could not get the logs on feature on this rig tomoroow i will try my other rig 
i did get this error 
tr: warning: an unescaped backslash at end of string is not portable

**Comment by doktor83** [comment]
That's not an error, it's just hive's normal message. if you are on an older hiveos try updating to a newer one, with newer opencl drivers.

**Comment by tonybeesknees** [comment]
updated both rigs and still same problem 
both rigs never submit a share 

i can not turn logs on on both rigs to get miner logs

**Comment by doktor83** [comment]
tomorrow i will try my rx580 on hiveos with verus, and we will see if it's working

**Comment by tonybeesknees** [comment]
Thanks

**Comment by tonybeesknees** [comment]
i tried 4 rx580  andsame results no submited shares

**Comment by doktor83** [comment]
Latest hiveos, miner 1.0.9:
GPU1 is rx580

![Untitled](https://user-images.githubusercontent.com/6808360/193393668-6591c2f2-076d-43f7-89ad-e6f460c7eb45.jpg)

**Comment by tonybeesknees** [comment]
![Capture](https://user-images.githubusercontent.com/86913574/193433090-15741fc5-a37b-4978-aa6c-b07b3f1530ed.PNG)
![Capture](https://user-images.githubusercontent.com/86913574/193433110-f9327b72-81f1-4072-bc4b-5fa6ffc5165e.PNG)

**Comment by tonybeesknees** [comment]
latest hiveos and srbmier 
no joy

**Comment by doktor83** [comment]
it's not the latest you are on driver 20.40, latest uses 21.5

**Comment by tonybeesknees** [comment]
thank you very much 
![Capture](https://user-images.githubusercontent.com/86913574/193445144-175255ef-7a1b-4693-8499-690d2b5a0c52.PNG)

i run a update with 
hive-replace -y
so it done a fresh install latest stable version

**Comment by doktor83** [comment]
at least now i know verushash not working properly on polaris and 20.40 drivers.
