### ISSUE TITLE
help please i just want to mine some fractions of cryptocurrencies with my gpu

### ISSUE THREAD

**Issue by aprenminer** [doktor83/SRBMiner-Multi#142]
I want to ask a question.
I have searched many forums for a mining software for my amd R5 M330 card and I always get messages from software developers closing my topic and just saying that I can't mine with an R5 card. because it is an integrated for laptop. It is not like this. In fact my laptop has 2, one is the Intel one that comes with the processor. the other is an amd R5 m330. My question is why this negativity of this graph.
I just want to mine small fractions of some cryptocurrencies and even the software will not be free, always in this software a small fee is paid to the creator.
I don't understand. why discourage someone like that. If I had the money to buy a GPU I would definitely do it. Cryptocurrencies are disappointing, many poorly used GPUs.
Why can't I use my gpu? If I want to use my R5, the electricity consumption is at my own expense. I know it's no longer profitable to mine some algorithm with my graph, but it's all my hashrate power.

**Comment by doktor83** [comment]
Im not interested in adding support for it, sorry.
