### ISSUE TITLE
added experimental support for DNS-over-HTTPS

### ISSUE THREAD

**Issue by qiukeln** [doktor83/SRBMiner-Multi#143]
Hi guys! 
 added experimental support for DNS-over-HTTPS please  
just like teamredminer

  --dns_https=URL       Enables pool DNS resolution using DNS-over-HTTPS.  This is an experimental feature.  TRM only
                              supports the JSON-based variant, not the mechanism defined later in RFC8484.  The user must
                              provide the full https url including the method name.  It is allowed to pass hostnames
                              rather than raw IP addresses, but such hostnames will be resolved using system DNS.
                              The following are a few examples that have been verified to work:
                              
                              --dns_https=https://8.8.8.8/resolve           (Google DNS)
                              --dns_https=https://9.9.9.9:5053/dns-query    (Quad9)
                              --dns_https=https://1.1.1.1/dns-query         (Cloudflare DNS service)

**Comment by qiukeln** [comment]
> Hi 

- [ ] 

- [ ] guys! added experimental support for DNS-over-HTTPS please just like teamredminer

> 
> --dns_https=URL Enables pool DNS resolution using DNS-over-HTTPS. This is an experimental feature. TRM only supports the JSON-based variant, not the mechanism defined later in RFC8484. The user must provide the full https url including the method name. It is allowed to pass hostnames rather than raw IP addresses, but such hostnames will be resolved using system DNS. The following are a few examples that have been verified to work:
> 
> ```
>                           --dns_https=https://8.8.8.8/resolve           (Google DNS)
>                           --dns_https=https://9.9.9.9:5053/dns-query    (Quad9)
>                           --dns_https=https://1.1.1.1/dns-query         (Cloudflare DNS service)
> ```



> Hi guys! added experimental support for DNS-over-HTTPS please just like teamredminer
> 
> --dns_https=URL Enables pool DNS resolution using DNS-over-HTTPS. This is an experimental feature. TRM only supports the JSON-based variant, not the mechanism defined later in RFC8484. The user must provide the full https url including the method name. It is allowed to pass hostnames rather than raw IP addresses, but such hostnames will be resolved using system DNS. The following are a few examples that have been verified to work:
> 
> ```
>                           --dns_https=https://8.8.8.8/resolve           (Google DNS)
>                           --dns_https=https://9.9.9.9:5053/dns-query    (Quad9)
>                           --dns_https=https://1.1.1.1/dns-query         (Cloudflare DNS service)
> ```

- 
Duplicate of #

**Comment by doktor83** [comment]
or just use the --proxy option

**Comment by qiukeln** [comment]
> or just use the --proxy option
Okay!  Because I have tried to use two different agent software before. but failed. As a result, I cannot connect to the ore pool. The SRBminer is a very good software, but I was unable to use it. Thank you anyway!
