### ISSUE TITLE
XDAG / new equal pool setting

### ISSUE THREAD

**Issue by FSOL06** [doktor83/SRBMiner-Multi#144]
Hi.

Pool for equal mining o xdag.org have change. equal.xdag.org:13656 musst be replace by xdag.org:13656.

![image](https://user-images.githubusercontent.com/97795464/194766273-a9e57628-587a-475d-8354-51b83195a029.png)

Please find above start-mining-dagger.bat with correct settings :

> :: This is an example you can edit and use

> :: There are numerous parameters you can set, please check Help and Examples folder
> 
> @echo off
> cd %~dp0
> cls
> 
> SRBMiner-MULTI.exe --disable-gpu --algorithm xdag --pool xdag.org:13656!xdagmine.com:13654 --wallet your-wallet-here --worker srbminer
> pause

Thanks for update it in SRBMiner future releases.

Regards.

**Comment by doktor83** [comment]
It will be done.
