### ISSUE TITLE
Error loading miner

### ISSUE THREAD

**Issue by szentigrad3** [doktor83/SRBMiner-Multi#152]
https://i.imgur.com/1jZ2cud.png

**Comment by doktor83** [comment]
windows server? got a few previous reports, i dont know what to do with it sorry.

**Comment by szentigrad3** [comment]
Windows 11

**Comment by doktor83** [comment]
i might test it on win11 one day, but right now im more focusing on linux bases mining os-es and win10 - that's what i already have.
