### ISSUE TITLE
SHA256 Support

### ISSUE THREAD

**Issue by JayBitron** [doktor83/SRBMiner-Multi#155]
Hello,

We recently created a sha256 coin named Lyncoin, but people was wondering if there are any AMD miner, so I'm asking you can you please add support for sha256 algorithm just like bitcoin?

Thank you!

**Comment by doktor83** [comment]
Hi, there are GPU miners for SHA256. I am not going to add it, no sense competing with GPU against asics that run SHA256.

**Comment by JayBitron** [comment]
It doesn't have to be competing, it's a tool for mining, my pool even allows cpu miners.
