### ISSUE TITLE
Please add fan speed control parameter for nvidia

### ISSUE THREAD

**Issue by namescmyta** [doktor83/SRBMiner-Multi#157]
And we're all set. =P Have a nice day!
...
Maybe gddr6x temp sensor readings one day.. yikes! Just one issue at a time.

**Comment by Jimvis** [comment]
![Безымrrrrrrrrянный](https://user-images.githubusercontent.com/114290244/215869750-69e87b8f-a935-40e3-82c8-aed88f7214f2.jpg)   does not work

**Comment by doktor83** [comment]
next time check the list of supported algorithms.

**Comment by Jimvis** [comment]
-a yescrypt I'm trying this script
