### ISSUE TITLE
Miner attempts to mine even though the dataset hasn't been fully created, resulting in invalid shares submitted

### ISSUE THREAD

**Issue by jchoi071** [doktor83/SRBMiner-Multi#16]
Windows 10, miner version 0.6.5, mining Ergo on CPU
Upon startup or new job received, the miner mines without waiting for the block dataset to be created, causing invalid shares to be submitted to the pool. Once the dataset is fully created, only valid shares are submitted until the next job is received. Occasionally the miner will wait for the dataset to be created, but usually it doesn't wait.

Pastebin: https://pastebin.com/3NbALchW

**Comment by doktor83** [comment]
i might look into it, but its not priority work, cpu mining autolykos isn't really a profitable thing.
