### ISSUE TITLE
PARSE error Mining Progpow_veil

### ISSUE THREAD

**Issue by ohcee** [doktor83/SRBMiner-Multi#160]
Getting this error when trying to mine progpow__veil. They had a dag reduction recently. That could be the reason why?

![Screenshot 2023-01-30 at 8 07 25 PM](https://user-images.githubusercontent.com/46406370/215660969-906023ee-0e95-41a6-b738-fb020f024ed0.png)

**Comment by doktor83** [comment]
i have no idea, not following what's happening with veil. Now that wooly removed it, there is no more public pools for it.

**Comment by ohcee** [comment]
people are still solo mining it until another pool opens. i was trying to to find an alternate to Trex miner and wildrig
