### ISSUE TITLE
Dual mining on AMD GPU

### ISSUE THREAD

**Issue by sfalas01** [doktor83/SRBMiner-Multi#168]
Tested on RX580 4GB (lots of combos are still sufficient to dual mine with 4GB).

The miner works correctly but for some reason, it takes a very long time to start mining. The mining window is stuck at the loading phase as seen below:
![image](https://user-images.githubusercontent.com/22576563/221032314-0b65e3e2-c5f2-49e4-a25e-377c604e991e.png)
It might take up to 5+ minutes to start mining.
On Nvidia, this problem does not seem to exist.

**Comment by doktor83** [comment]
its not a gpu issue. This pause can occur if the devfee pool/pools connection of the algorithm/s you mine can't be connected. It's trying until it succeeds or if not, miner will exit.

**Comment by sfalas01** [comment]
> its not a gpu issue. This pause can occur if the devfee pool/pools connection of the algorithm/s you mine can't be connected. It's trying until it succeeds or if not, miner will exit.

Using an Nvidia GPU on the same pools connects just fine though. And they are both on the same network.

**Comment by sfalas01** [comment]
> its not a gpu issue. This pause can occur if the devfee pool/pools connection of the algorithm/s you mine can't be connected. It's trying until it succeeds or if not, miner will exit.

Ok so, I narrowed this down to a VPN causing the issue. However, other miners seem to be unaffected. Any ideas on what might be the issue with the VPNs configuration?

**Comment by doktor83** [comment]
dns probably. Im closing this cause its not a miner issue.
