### ISSUE TITLE
Setup GPU devices

### ISSUE THREAD

**Issue by tahaqutbuddin** [doktor83/SRBMiner-Multi#169]
I am running this code on Linux based EC2 instance. How can I use the GPU of my instance as there is no gpu in list-devices file. 

I also tried to using the param --gpu-boost 3 in the mining file but it didn't work.

what I am receiving is:- 
CPU and GPU both are disabled. Enable one of them

**Comment by doktor83** [comment]
you didnt tell which gpu's (amd, nvidia), but you are probably missing drivers or opencl

**Comment by tahaqutbuddin** [comment]
I am using g4ad.xlarge right now for mining ERGO. And yes I am familiar with setting up cpu based mining but unable to proceed with gpu one. If possible can you guide me in steps, what to perform?

G4ad has these specs:-
2nd Generation AMD EPYC Processors (AMD EPYC 7R32)
AMD Radeon Pro V520 GPUs

**Comment by doktor83** [comment]
There are plenty of tutorials on the internet on how to install amdgpu-pro drivers.
Closing this as its not a miner issue.
