### ISSUE TITLE
No GPU devices listed in ./list-gpu-devices.sh

### ISSUE THREAD

**Issue by tahaqutbuddin** [doktor83/SRBMiner-Multi#171]
I am using Linux instance g4ad.xlarge with AMD pro radeon AMI and after I ran this command 

wget https://github.com/doktor83/SRBMiner-Multi/releases/download/2.1.0/SRBMiner-Multi-2-1-0-Linux.tar.xz && tar -xvf SRBMiner-Multi-2-1-0-Linux.tar.xz && cd SRBMiner-Multi-2-1-0 && miner stop && cp SRBMiner-MULTI /hive/miners/srbminer/2.0.2 && miner start

I didn't found any list of GPUs in the list-gpu-devices.sh file

**Comment by tahaqutbuddin** [comment]
No matter whatever AWS instance or AMIs, I use. The list-gpu-devices.sh file is empty. Though I have installed the Nvidia drivers and I have Tesla 4 gpu.

**Comment by alexgabbard01** [comment]
How are you able to obtain Tesla T4 on AWS? Is it not more expensive to run cloud GPU's for mere mining? As it stand GPU mining is barely profitable. I can help if you can answer my question

**Comment by tahaqutbuddin** [comment]
I am using Spot request
