### ISSUE TITLE
why don't you answer Please at least say why I don't have the right to an answer

### ISSUE THREAD

**Issue by majfo** [doktor83/SRBMiner-Multi#173]
why don't you answer
I was mining alepium \ kaspa --gpu-cclock 1305 --gpu-mclock 810 --gpu-plimit 170 . And my graphic card was blocked in fan o pl 5% cclk 210mz mclk 810. If you overclock with or miner it changes but without the miner it is blocked in the values that I mentioned and not even with the gpu tweak lll it does not return to the normal values of rtx3600. Can you help me please. 
 Please at least say why I don't have the right to an answer  THANKS
![IMG_20230307_005908](https://user-images.githubusercontent.com/127163457/223581109-79a61e53-070f-449a-ac15-1943fa64801d.jpg)
![IMG_20230307_005926](https://user-images.githubusercontent.com/127163457/223581166-9e1a7907-69d8-462b-a9ff-cf56fd7c0688.jpg)

**Comment by majfo** [comment]
Please at least say why I don't have the right to an answer

**Comment by doktor83** [comment]
restart computer problem solved.

**Comment by majfo** [comment]
that was the 1st thing i did. I already installed new maderbord bios, windows11, drivers, programs, miner, etc. I've done several health tests and nothing and that's why I asked for help. don't you have a program to clean the overclocks? thanks
