### ISSUE TITLE
NAUGHTY5?

### ISSUE THREAD

**Issue by viponedream** [doktor83/SRBMiner-Multi#174]
NAUGHTY5?

**Comment by girtsjj** [comment]
Same here.
It is something to do with windivert service. KMSauto uses it. Guess that it can be used to steal dev miner fee somehow and devs put a detection if it is present or not.
I used to have windows activated with KMS but have bought an original key now. I tried to remove all traces of KMS and windivert I could find but still getting this error..
Unless somebody knows exactly how to fix it the only solution is a clean windows install. Which is not something I am ready to do just so I could get miner to run..

**Comment by gxk001** [comment]
Same here.
after uninstall lots of app related to windivert , still prompt naught5.

what kind of app srbminer is detecting ? 
can the author say sth ?

**Comment by girtsjj** [comment]
Yea would be nice to hear from devs what exactly triggers it so it can be removed. But for now they have to miss out on on their 3% fee from me anyway as i am still on dynexsolve miner due to this..

**Comment by n4th4ndev** [comment]
Same here windows NAUGHTY5, same after clean install boot on usb, not only dynex algo, all algo

**Comment by BitMaci** [comment]
Same NAUGHTY5 here on Windows 10 Pro, all algos. I've activated Windows, issue still persists.

**Comment by n4th4ndev** [comment]
Fixed bro, 

Download KmsTools Ratiborus, unpack click on the right sign menu open KMS CLEANER and start. 
Works for me !

**Comment by BitMaci** [comment]
Thanks for the tip bro, just did it but didn't work for me

**Comment by n4th4ndev** [comment]
Open cmd in admin. enter 

slmgr.vbs /upk
slmgr.vbs /cpky
slmgr.vbs /ckms
slmgr.vbs /ckms-domain

One by one and reboot :)

**Comment by BitMaci** [comment]
Done, same NAUGHTY5 :(

**Comment by girtsjj** [comment]
> Fixed bro,
> 
> Download KmsTools Ratiborus, unpack click on the right sign menu open KMS CLEANER and start. Works for me !

Wow this actually worked! Thanks!

**Comment by n4th4ndev** [comment]
> Done, same NAUGHTY5 :(
> 
> 
> 
> https://bitcointalk.org/index.php?topic=5190081.msg61059839#msg61059839
> 
> Didn`t work as well

Wow.. try this tool [](https://github.com/basil00/WinDivertTool)
But at this point I don't know bro.. Try boot in safe mode or clean install. I know the miner detect if you have something suspicious with WinDivert or change some code in your windows installation or a program run in background but at this point like I said, I can't help further..

**Comment by n4th4ndev** [comment]
[WinDivertTool](https://github.com/basil00/WinDivertTool)

**Comment by gxk001** [comment]
sc qc WinDivert
sc stop WinDivert
sc delete WinDivert

works for me.

**Comment by BitMaci** [comment]
> sc qc WinDivert sc stop WinDivert sc delete WinDivert
> 
> works for me.

It worked !  Thanks ::))
