### ISSUE TITLE
Error -4 on Windows

### ISSUE THREAD

**Issue by noebranco** [doktor83/SRBMiner-Multi#176]
This keeps repeting in miner...
![imagem](https://user-images.githubusercontent.com/48280825/223881383-d28c9465-db4f-4491-bfca-a090e332b330.png)

**Comment by Raizly-Max** [comment]
I have same problem with my 1660ti, but 4070ti works well. And 1660ti works well in another miner.

**Comment by noebranco** [comment]
I have 2 1660ti on this rig and a 3060 and a 3060ti.
I'm going to try 1 card at a time to see what happens.
Thanks.

**Comment by noebranco** [comment]
Thanks so much I'm going to try that. :-)

**Comment by Raizly-Max** [comment]
> add ' --gpu-intensity nnn' to your command line. nnn has to be lower than what you see in '[2023-03-09 11:17:39] A0|GPU0 | [BUS:0b] [I: **376**]'. Lower the value until the error goes away.

It is works, thanks!

 Hmm, my 1660ti now shows unreal hashrate, it's strange. But why is the frequency of the GPU in the miner lower than actually in the GPU-Z and MSIAfterburner?

[https://imgur.com/a/DB0vb7T](url)

**Comment by noebranco** [comment]
Thanks so much. Worked for me too :-)
