### ISSUE TITLE
Dynex CPU пипец грузит

### ISSUE THREAD

**Issue by Eujenvanino** [doktor83/SRBMiner-Multi#177]
I3-6100 нормально только 4 видеокарты 3080 может, а потом хешь на пуле валится
Как исправить?
На всех ригах такие проблемы

**Comment by bekman1** [comment]
tolko i5 ili i7 spaset.
U menja tozhe takaja problema na nekotorih rigah gde i3. Skinj razgon jadra i pamjati. Nemnogo pomozhet.

**Comment by Eujenvanino** [comment]
У меня память вобще в минусе

**Comment by bekman1** [comment]
nu togda upgrade materi s procami i5 10+ pokolenie
Normalno rabotajut rigi (8GPU, Linux, 8GB RAM), tolko s i5-9400F i vishe.

i3-10100F ezhe kakto spravljaetsja LA 7.5

**Comment by bekman1** [comment]
a esli pamjat razgonish, to hashrate prosto uletaet, no tut somnenie, chto on vesj dohodit do pula. Netu indikatora hashrata na storone pula,,,

**Comment by Eujenvanino** [comment]
у меня мамки на 12 карт так что туда процессоры V2 не идут

**Comment by bekman1** [comment]
vsegda govoril, chto optimalno eto 8 kart v rige.
Nu huli, togda odna nadezhda, chto pofiksjat LA

**Comment by Eujenvanino** [comment]
места нет

**Comment by KMNdev** [comment]
а какой хр на 3080 ?

**Comment by Eujenvanino** [comment]
550 если не нагружать

**Comment by UselessGuru** [comment]
When you write in Englisch we might be able to help ;-)

**Comment by denstrelkowsky** [comment]
> When you write in English we might be able to help ;-)

The problem is high CPU load.  If I overclock GPU Load Average (LA) will be equal 7.0. My config is : i7 7700 and 6*RX6600 (2500H/s)
Please find screenshot below
![image](https://user-images.githubusercontent.com/56365853/224367761-70938f57-d964-4c09-9e06-e5ef545c3195.png)
celeron g3960 can handle only 750h/s
