### ISSUE TITLE
0.5.6 M7M:  Internet not found! Please insert internet into miner

### ISSUE THREAD

**Issue by Quake4** [doktor83/SRBMiner-Multi#18]
```
SRBMiner-MULTI.exe --algorithm m7mv2 --pool m7m.eu.mine.zpool.ca:6033 --wallet xxx --password c=BTC,Home  --api-enable --api-port 4040 --miner-priority 1 --disable-gpu --retry-time 5 --nicehash false --tls false
```
![image](https://user-images.githubusercontent.com/29517243/107688448-b1574180-6cb8-11eb-8219-9a19d9b20ae6.png)

**Comment by doktor83** [comment]
firewall or antivirus blocking miner access to **srbminer.com**

**Comment by Quake4** [comment]
no blocking
![image](https://user-images.githubusercontent.com/29517243/107885248-35543800-6f0a-11eb-94ad-a2c04de9bfe6.png)

**Comment by Quake4** [comment]
if i remove api port and api enable, it will work
```SRBMiner-MULTI.exe --algorithm m7mv2 --pool m7m.eu.mine.zpool.ca:6033 --wallet xxx --password c=BTC,Home --miner-priority 1 --disable-gpu --retry-time 5 --nicehash false```

**Comment by doktor83** [comment]
it's not related to those parameters, it's only related to if miner can connect to get the list of devfee pools or not

**Comment by doktor83** [comment]
also version 0.5.6 ? it's a little bit too old..
