### ISSUE TITLE
GPU OC --gpu-moffset FAILED

### ISSUE THREAD

**Issue by 253919780** [doktor83/SRBMiner-Multi#183]
The graphics card overclocking parameter (--gpu-moffset) setting fails when running

**Comment by doktor83** [comment]
which OS, driver version and GPU ?

**Comment by 253919780** [comment]
windows 528.24 2070

doktor83 ***@***.***>于2023年3月9日 周四20:12写道：

**Comment by SoulRipper888** [comment]
Same here: Windows 10 LTSC 2021, RTX 3080 with 528.24 drivers.

**Comment by doktor83** [comment]
only windows has this issue. going to be fixed in next release.
