### ISSUE TITLE
Error while creating GPU workers

### ISSUE THREAD

**Issue by Shar2** [doktor83/SRBMiner-Multi#184]
Error while creating GPU workers..
Pver and over again.
![image](https://user-images.githubusercontent.com/49821454/224024466-7fbd38e2-9f90-4da3-a765-fd02cf9eb503.png)
Not aggressive OC:
![image](https://user-images.githubusercontent.com/49821454/224024553-69c15194-be0c-4db4-98e5-eda2c210edb2.png)

**Comment by GrackleOSpite** [comment]
![image](https://user-images.githubusercontent.com/127457025/224192753-be32f013-85a9-4e98-b213-136a526c127e.png)
Same but different problem!

**Comment by VDreaming** [comment]
Same  problem!
![856c77c63832cc635a19fe0fdab4c78](https://user-images.githubusercontent.com/31036735/224220973-8a9c2995-a30a-4fb8-abdd-4c7bfd2d2b40.png)

**Comment by doktor83** [comment]
just try setting --gpu-intensity manually see if it helps
