### ISSUE TITLE
Error -5 [clEnqueueWriteBuffer [_input_buffer]] [[BUS:03] (Thread 0)]

### ISSUE THREAD

**Issue by guillep2486** [doktor83/SRBMiner-Multi#186]
Alguien sabe porque en hiveos me sale este error Error -5 [clEnqueueWriteBuffer [_input_buffer]] [[BUS:03] (Thread 0)]

**Comment by lazy-tinker** [comment]
Lower overclock settings. Core offset was the issue on my rigs.

**Comment by doktor83** [comment]
or lower --gpu-intensity value
