### ISSUE TITLE
Not connected to a pool. Algo Dynex.

### ISSUE THREAD

**Issue by brain-5** [doktor83/SRBMiner-Multi#190]
Hello. I have some problems with connect to dynex pools:

<img width="734" alt="image" src="https://user-images.githubusercontent.com/898682/224607579-f246f6c1-31c0-471d-8299-c29821b8143d.png">

Command line:
`
SRBMiner-MULTI.exe --disable-cpu --algorithm dynex --mallob-endpoint 45.76.89.248:8081,51.178.74.173 --pool dynex.neuropool.net,dnx.eu.ekapool.com --wallet my_wallet --password %computername% --ssl false --api-enable
`

Tested on windows versions SRBMiner-MULTI 2.2.0 and 2.2.1.

Can't connect to dnx.eu.ekapool.com, dynex.neuropool.net. It worked two days ago.
Can you help me?

**Comment by doktor83** [comment]
there are no ports defined for the pools ...

**Comment by brain-5** [comment]
Ok. Thanks.
