### ISSUE TITLE
Worker name is not sent for `blake3_ironfish`

### ISSUE THREAD

**Issue by charlie-wasp** [doktor83/SRBMiner-Multi#191]
Hi there

I noticed, that srbminer does not send worker name via stratum for Ironfish, however I've set it with `--worker` option

I use version 2.2.0 on HiveOS with these parameters:

```
--gpu-id 0 --algorithm blake3_ironfish --pool ... --wallet %WAL% --worker coolworker
```

Here is `mining.subscribe` payload:

```
{"id":1,"method":"mining.subscribe","body":{"version":1,"publicAddress":"7d09...f1e"}}
```
So only wallet address is available. Is there something wrong with my setup?

**Comment by lazy-tinker** [comment]
try using --password instead

**Comment by charlie-wasp** [comment]
> try using --password instead

interesting idea, but doesn't make any difference 🤔

**Comment by doktor83** [comment]
i need to remove that parameter, it only confuses people. --worker was for some cryptonote coins.
How to define the worker name depends only from the pool. Usually its wallet.worker or in the password field etc.
You can find this info on the pool's website.
