### ISSUE TITLE
RaveOS custom build

### ISSUE THREAD

**Issue by Kekkonshiki** [doktor83/SRBMiner-Multi#192]
Can you release custom build for RaveOS?

For the current release 2.2.1, you just need to put the actual SRBMiner-MULTI in the archive :-)

![image](https://user-images.githubusercontent.com/12028666/224870134-acfb3d3e-f947-4202-9303-c9430cee3f53.png)
[custom-raveos-SRBMiner-Multi-2-2-1.zip](https://github.com/doktor83/SRBMiner-Multi/files/10963385/custom-raveos-SRBMiner-Multi-2-2-1.zip)

**Comment by doktor83** [comment]
i dont like to do these custom builds, i added hiveos only because too many people asked me to do it. you are the first to ask for raveos so ..
