### ISSUE TITLE
The Hiveos dont download the Custom your SrBminer

### ISSUE THREAD

**Issue by linuxfree2016** [doktor83/SRBMiner-Multi#193]
Please tell if need have last stable hiveos for can download and install

2 images show the error 
![IMG_20230314_090719502](https://user-images.githubusercontent.com/20795040/224996843-c6985bd7-25e3-43a1-b9c6-b256c626fb09.jpg)
![IMG_20230314_090746022](https://user-images.githubusercontent.com/20795040/224996923-dae8746b-3058-438f-a315-91a13bb40d6c.jpg)

**Comment by doktor83** [comment]
then complain to hiveos maybe

**Comment by linuxfree2016** [comment]
Do you use last version of Hiveos cause i have from init january 2023 and
Download not work.

Em terça-feira, 14 de março de 2023, doktor83 ***@***.***>
escreveu:
