### ISSUE TITLE
2.2.1 error with dynex

### ISSUE THREAD

**Issue by Damien3131** [doktor83/SRBMiner-Multi#194]
Hello

I have a lot of 
GPU0[t0] result rejected [invalid share err#414] [dynex][0]
errors that take down my hashrate a lot (about 50%).
RTX3060 et RTX 3070
I am quite sure there is a big trouble somewhere.

Best regards

**Comment by doktor83** [comment]
trouble is you need to update to latest 2.2.1. Or if in hiveos then use it through the GUI, and not the custom miner.
