### ISSUE TITLE
huge pages available but not enabled

### ISSUE THREAD

**Issue by Shahraiz-akhtar** [doktor83/SRBMiner-Multi#196]
hi, i'm in urgent need of support from anyone who could tell me how to enable my available huge pages in srbminer. i am running windows 10 pro and the latest version of srbminer(2.2.1), i have followed everything to get them available through local security policies, but still it doesnt say it is enabled, just says available due to which my hashrate doesn't increase. i am attaching the screenshot of my srbminer screen where it says huge pages available. Please help me in getting it enabled. thanks in advance!
[huge pages unavailable](https://user-images.githubusercontent.com/127963100/225338458-44735901-6ad0-4f7c-862a-42f2de6901e5.jpg)

**Comment by UselessGuru** [comment]
You must run SRBminer with administrative rights.

**Comment by Shahraiz-akhtar** [comment]
Thanks for the response, I'm running it as an administrator still to no avail :(

**Comment by doktor83** [comment]
If it says its available then it will use it - if its available. It wont say its 'enabled'.
