### ISSUE TITLE
Error -4 after adding  a 4th GPU

### ISSUE THREAD

**Issue by IntensityShai** [doktor83/SRBMiner-Multi#197]
I added a 4th GPU and got the below error message.
Anyone else having this problem?

Error -4 [clEnqueueNDRangeKernel [_kernel_dynex_0]] [[BUS:05] (Thread 3)]

![image](https://user-images.githubusercontent.com/128010649/225494466-8dd9c9e5-6618-4b7e-b1cd-0740ecca4cce.png)

**Comment by gxk001** [comment]
seems 3090?
try set total pagefile size = total card's ram size,
eg, 
set OS total pagefile size = 24G*4=96G

**Comment by doktor83** [comment]
just lower the intensity manually on that gpu. as stated in the release notes

**Comment by gxk001** [comment]
l have 4 3090 too.
same error with you.
set "--gpu-intensity 1480!1480!1480!892"   did work.

but ,for some reason, i can not set pagefile > 96G ,  only set 84G，
after some test： (1480*3 +892 )*16M = 84G ， if i set last gpu's intensity > 892,  srbminer will give me that error.

![image](https://user-images.githubusercontent.com/32119424/225650268-1c13337d-48ef-4cca-80f0-baf1f99944f6.png)

**Comment by IntensityShai** [comment]
doktor83: THANK YOU - i lower the intensity and got it to work.
gxk001: I got mine to work at 
1400!1400!1400!800

This is where i change my page file.
![image](https://user-images.githubusercontent.com/128010649/225769602-a89b0fa0-77a6-4057-b950-1acb6ba2e87a.png)

**Comment by gxk001** [comment]
just want to know,  after you set pagefile = 100G and intensity=1480!1480!1480!1480 ,  you still got error msg ?

**Comment by IntensityShai** [comment]
No more error message after that.
I played around some more and was stable at 1420!1420!1420!1420
