### ISSUE TITLE
SRBMiner-MULTI v2.2.3 --gpu-cclock0 not working correctly on Hiveos.

### ISSUE THREAD

**Issue by woottj1** [doktor83/SRBMiner-Multi#204]
Hiveos

Individually setting core clock lock does not seem to work correctly.  ie. --gpu-cclock0 1470,1470,1470,1605,1470,1470

In my case all cards are showing core clock 1470.  This is seen by running Hiveos: nvtool --clocks
HiveOS Nvtool 1.7.9
DEVICE #0:
  GPU CLOCKS CURRENT: 1470 MHz
  MEM CLOCKS CURRENT: 7800 MHz
DEVICE #1:
  GPU CLOCKS CURRENT: 1470 MHz
  MEM CLOCKS CURRENT: 7800 MHz
DEVICE #2:
  GPU CLOCKS CURRENT: 1470 MHz
  MEM CLOCKS CURRENT: 7800 MHz
DEVICE #3:
  GPU CLOCKS CURRENT: 1470 MHz
  MEM CLOCKS CURRENT: 10501 MHz
DEVICE #4:
  GPU CLOCKS CURRENT: 1470 MHz
  MEM CLOCKS CURRENT: 10251 MHz
DEVICE #5:
  GPU CLOCKS CURRENT: 1470 MHz
  MEM CLOCKS CURRENT: 8300 MHz_

To correct I run: nvtool -i 3 --setclocks 1605

Now when I run nvtool --clocks
HiveOS Nvtool 1.7.9
DEVICE #0:
  GPU CLOCKS CURRENT: 1470 MHz
  MEM CLOCKS CURRENT: 7800 MHz
DEVICE #1:
  GPU CLOCKS CURRENT: 1470 MHz
  MEM CLOCKS CURRENT: 7800 MHz
DEVICE #2:
  GPU CLOCKS CURRENT: 1470 MHz
  MEM CLOCKS CURRENT: 7800 MHz
DEVICE #3:
  GPU CLOCKS CURRENT: 1605 MHz
  MEM CLOCKS CURRENT: 10501 MHz
DEVICE #4:
  GPU CLOCKS CURRENT: 1470 MHz
  MEM CLOCKS CURRENT: 10251 MHz
DEVICE #5:
  GPU CLOCKS CURRENT: 1470 MHz
  MEM CLOCKS CURRENT: 8300 MHz

**Comment by doktor83** [comment]
it works, but you didnt specify which cards you want to use with --gpu-id
