### ISSUE TITLE
Error in mining dynex coin on amd gpu RX570 AND RX6600XT

### ISSUE THREAD

**Issue by Tanishq242** [doktor83/SRBMiner-Multi#208]
it showing mallob registration [0]
it showing mallob registration [1]
it showing mallob registration [2}
![gfdg](https://user-images.githubusercontent.com/128801254/227496414-2a7b004f-c81d-4b11-8fee-37c5e3817c10.png)

**Comment by doktor83** [comment]
Mallob issues are dynex issues, not miner issues. Seek for help in dynex discord.

**Comment by Tanishq242** [comment]
okay
