### ISSUE TITLE
Smooth switchover on dual-mine

### ISSUE THREAD

**Issue by megalolka** [doktor83/SRBMiner-Multi#210]
Hello!
Here is the GPU-Z diagram of GPU load when dual-mining progpow_epic + progpow_sero.
We can see the power dropdowns when SRBminer switches between algos.
The CPU load is 60-80% all the time, not more.
Such power drop downs are very bad for power supply. 
Can you make some optimization of algo switching? 
![SRB1](https://user-images.githubusercontent.com/76410679/227615605-ffd29f68-fd2b-4dcd-9e6a-d56589a64fca.jpg)

And here is the GPU-Z diagram of the same dual-mining on the same 12 GPUs rig using TT-miner.
Algo switching is very smooth.
And the CPU load is 10-20%, not more.
I have very big quantity of such 12 GPU rigs and I want to move from TT to SRB. But I need a stable power draw because overwise the power supplies can fail soon.
![SRB2](https://user-images.githubusercontent.com/76410679/227617144-fd969f08-4f1b-43ab-a065-642e2c879e1f.jpg)

**Comment by doktor83** [comment]
You have those big gaps because of the OC switch. Is TTMiner switching your OC on algo change?

**Comment by megalolka** [comment]
No, I did not use any OC options in SRB.

**Comment by doktor83** [comment]
So why does the core clock go up on every algo change if you didnt use OC in miner ?

**Comment by doktor83** [comment]
I will take a look but no eta when, got priority stuff first

**Comment by megalolka** [comment]
> So why does the core clock go up on every algo change if you didnt use OC in miner ? I mean if you lock clocks then driver shouldnt change it ?

My OC settings are: 
c:\windows\system32\nvidia-smi.exe -lgc 2040
c:\windows\system32\nvidia-smi.exe -pl 104

And there is no OC in SRB:
SRBMiner-MULTI.exe --disable-cpu --algorithm progpow_epic;progpow_sero --multi-algorithm-job-mode 3 --disable-gpu-amd --disable-gpu-intel --gpu-off-temperature 68 ^
--pool 1.2.3.4:3416;1.2.3.4:8080 --wallet XXX;YYY --password X;X --worker Z;Z --log-file c:\temp\SRB.txt --gpu-intensity 22;22 --send-stales 1 --disable-gpu-tweaking 

So, when the GPU is not busy by a heavy computing, the chip works at 2040 MHz.
Otherwize it reduces the clock to have power limit at 104W.

> Also those gaps are really big, seconds. The switch isnt taking so long, its instant.

Yes, may be this idle gaps take 1-2 seconds.
May be it's because of high CPU load? 
SBR loads Celeron 3900 to 60-80% (other miners loads not more than 20-30%).
May be it's possible to optimize some CPU usage (like "don't check shares on CPU" option, etc.)...

**Comment by megalolka** [comment]
I have checked the situation on one of my small rigs - 6 * RTX 3060 with Intel I5 CPU. 
CPU is loaded upt o 40-50% but the idle gaps are the same.
So now I beleive it's not a CPU issue.
The log shows 3 seconds delay between "working on EPIC jpbs" and "EPIC job received". May be the problem somewhere between these 2 messages?
====================== 
[2023-03-25 11:54:54] Working on algorithm 0 jobs
[2023-03-25 11:54:57] Job received [1] block height 1890277 [progpow_epic][0]
[2023-03-25 11:54:57] Job received [0xc022acc80fae8fe06989a53e5d5d9a] block height 9853955 [progpow_sero][1]

**Comment by doktor83** [comment]
high cpu usage is because im using opencl , and the others (majority for nvidia) uses cuda. There is a stupid thing in nvidia opencl drivers that they dont want to fix for ages that pushes the cpu usage to 100% so im doing some workarounds to bring that down as much as i can. There is no such issue when using cuda.
Ill leave this issue open and when i get time i will check what is happening.

**Comment by doktor83** [comment]
Try something, set **--oc-delay 0**
Looks like i am doing a delay on algoswitch even if no OC settings are applied. This is probably what's causing the stalls/delays.
I fixed it for the next release

**Comment by megalolka** [comment]
--oc-delay 0 parameter works!
Now there are no delays
Thank you very much!

**Comment by doktor83** [comment]
yeah, that was a mistake i made and fixed for next release. Thanks for reporting it!
