### ISSUE TITLE
Bug : not support on Nvidia 4090 GPU 

### ISSUE THREAD

**Issue by Silapakt** [doktor83/SRBMiner-Multi#212]
srbminer 2.2.3
GPU : Nvidia 4090
Windows 10 
CPU i7-870
RAM 8 GB

i got 3500+ H/s
but very low result accept

My Config below

--disable-cpu 
--algorithm dynex 
--mallob-endpoint mallob.neuropool.net:8081 
--pool dynex.neuropool.net:19331

**Comment by doktor83** [comment]
It works on 4090, many users confirmed it. You can go to dynex discord / SRB channel to get help.
