### ISSUE TITLE
firo broken

### ISSUE THREAD

**Issue by Quake4** [doktor83/SRBMiner-Multi#213]
![image](https://user-images.githubusercontent.com/29517243/229294848-f0160666-3a6b-40e7-867e-e407ba00d739.png)

**Comment by doktor83** [comment]
FiroPow is not broken. 
StakeCube is broken. It's not using the exact same settings as FiroPow, but they say they use FiroPow....
Tried mining FIRO coin ?

**Comment by Quake4** [comment]
No, just benchmarking.
