### ISSUE TITLE
Intel A770 error GPU0 couldn't create buf6 [0]

### ISSUE THREAD

**Issue by cryptobueno** [doktor83/SRBMiner-Multi#226]
![DNX_A770](https://user-images.githubusercontent.com/71607110/230489626-86d026ef-c197-4357-8e42-bcec8cce69fb.JPG)

Running Win10, mining Dynex with SRBminer version 2.2.4.  Any ideas on a fix?

Thanks!

**Comment by doktor83** [comment]
need to manually set intensity. intel drivers are still bad, dont allow for allocation of big buffers
