### ISSUE TITLE
--gpu-mclock1 failed and rtx3090 got low hashrate.

### ISSUE THREAD

**Issue by sosme2012** [doktor83/SRBMiner-Multi#227]
--gpu-mclock1 failed and rtx3090 got low hashrate.
only got 19H/W
![1](https://user-images.githubusercontent.com/90928649/230742977-abb0662e-1cd0-4f79-b712-60f3e6830d0d.JPG)

**Comment by doktor83** [comment]
--gpu-mclock1 is used for ALGORITHM1. you are mining only DYNEX, so why use a parameter that is for the SECOND algorithm, when you dont have a SECOND algorithm ?
