### ISSUE TITLE
Dangerous power over load flaw in srb miner. this how to burn ur rig!

### ISSUE THREAD

**Issue by coolrip007** [doktor83/SRBMiner-Multi#229]
now run THOSE settings in srb miner and watch your rig blow baby!

right is u look at line #2! where its <   --gpu-offset 225  > ??? 
what is missing is the letter c!!! should be --gpu-coffset 225!!
 not --gpu-offset 225! with the c letter missing your rig will 
 power like a light house man! i triple dare to try that! be 
 warned and ready to pull the power plug from the wall! bro 
 and your fans will spend so loud and fast like roaring sound 
 in about 3 secs your psu is toast! i was mining dynex in hive os 
 newest image with srb miner! Ill do a youtube vid to prove it! 
 i did recreate it twice!

**Comment by coolrip007** [comment]
and i have an old mining rig to test it on! i hope your dev when u see this post will test it your self  and see and then then put safe guards into the software code.. all the settings are as follows

--gpu-cclock 1470
--gpu-offset 225
--gpu-mclock 5001
--dynex-cpu-pow 0
--disable-cpu-sync 1.195
--mallob-endpoint http://mallob.neuropool.net:8081/

the 2nd line is missing the c  ex should be --gpu-coffset 225 not --gpu-offset 225
if u do test this with the oc i did that blow my PSU! be ready to pull power plug or esle! telling u folks just do the experiment
and see for your self! i did post this flaw in srb discord !

**Comment by coolrip007** [comment]
if a hacker finds this flaw and start see folks rigs over power and burning rigs and homes down before of this flaw u srb miner have ! will be a sad day!

**Comment by auroracoin** [comment]
> now run THOSE settings in srb miner and watch your rig blow baby!
> 
> right is u look at line #2! where its < --gpu-offset 225 > ??? what is missing is the letter c!!! should be --gpu-coffset 225!! not --gpu-offset 225! with the c letter missing your rig will power like a light house man! i triple dare to try that! be warned and ready to pull the power plug from the wall! bro and your fans will spend so loud and fast like roaring sound in about 3 secs your psu is toast! i was mining dynex in hive os newest image with srb miner! Ill do a youtube vid to prove it! i did recreate it twice!

Post link to your youtube video plz :)

**Comment by coolrip007** [comment]
Sure just try it your self I discovered Your FLAW! just get an old mining rig u dont like and follow red pandda's vid on srb mioner and do his oc! but forget the c letter that sup to go --gpu-coffset 225 and out it --gpu-offset 225 so by mssing the letter c. it brun my psu! and i working to recreate like i did twice already! and film it ! becoz folks like u dont bleibve and seems like u will not even try it to SEE! so why email me? Im wokring with youtuber red panda and minesum101 and maybe son of tech my get me on the show and lets burn up some old mining rig! and it was the fuse that blow in the PSU! it toaste i tried to fix my by passing the fuse and its gone folks!//Mining cave psu quite 1,600 watts and man in 2 secs 2,000 watts hit so fast! i didnt have time to stop it! and it did it again but that time i had my hand on the power cord and saved that psu! so then i went over red panda vid again and saw i left the c out on the oc so i put that c in fornt like i missed and it mining great with dynex on srb miner! like really 1 letter missing can cause this to happen then i came across that dude vid below! and he has oc disclaimer! and said the same thing i starting saying be cafeful with OC and be safe ! 
red's How to mine Dynex, Radiant or Nexa in HiveOS.  

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
How to mine Dynex, Radiant or Nexa in HiveOS.


 |

 |

 |


How to mine Dynex, Radiant or Nexa in HiveOS.


thats BS ! i can redo too just leave the c off the setting --gpu-offset -225[11:59 PM]--gpu-cclock 1470--gpu-offset 225--gpu-mclock 5001--dynex-cpu-pow 0--disable-cpu-sync 1.195--mallob-endpoint http://mallob.neuropool.net:8081/[11:59 PM]now run THOSE settings in srb miner and watch your rig burn or fuse or break trip!  baby!
right is u look at line #2! where its <   --gpu-offset 225  > ??? what is missing is the letter c!!! should be --gpu-coffset 225!! not --gpu-offset 225! with the c letter missing your rig will  power like a light house man! i triple dare to try that! be  warned and ready to pull the power plug from the wall! bro  and your fans will spend so loud and fast like roaring sound  in about 3 secs your psu is toast! i was mining dynex in hive os  newest image with srb miner! Ill do a youtube vid to prove it!  i did recreate it twice!
recipe for burning rigs and homes if not careful! here i go talk to a non believer like its going to do any good coz u already believe what u want to believe without trying it and=d no proof!. well i have an old mining rig! and ill do a vid and post it on mu youtube channel Keith Savage (BJJ) . use that to fing it! youll see me old guy doing BJJ torments! i. so iT REAL AND WE ll I HAVE A NEW 1,600 PLAT EVGA psu!!! NICE! BUT I LOST A GREAT PSU $230 BUCKS DIOWN THE DRIAN BECOZ Y'ALL GUYS DONT HAVE any safe gurads! MOST THE TIME WHN I MISS UPA OC HIVE OS TELLS ME OR THE MINER JUST DONT WORK! BUT YOURS ON THE OTHER HAND! BURNS BROTHER !  
MUCH PEACE AND HOPE YA'LL FIX THIS ISSUE! IM NOT FOR ANY HAND OUTS JUST FIX IT ! 






i cant y'all u dont have any safe guards in your miner!!! even this dude said it happens to! BEST KASPA Overclock Settings Nicehash, Windows & HiveOS | 3060 3060Ti 3070 3070Ti 3080 3080Ti 3090 - YouTube

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
BEST KASPA Overclock Settings Nicehash, Windows & HiveOS | 3060 3060Ti 3...


 |

 |

 |




BEST KASPA Overclock Settings Nicehash, Windows & HiveOS | 3060 3060Ti 3070 3070Ti 3080 3080Ti 3090

said that i not put in the oc that miner will cause damage! and he has a disclaimer about the ocs! smart dude! 


    On Tuesday, April 11, 2023 at 11:48:15 AM CDT, uhliksk ***@***.***> wrote:  
 
 


I found interesting he's claiming to burn 1600 W PSU with 5x 240W 3070 GPUs running at 300W with total power surge of 2000W. I don't have a degree in mathematics but I feel something is wrong with this tale.

**Comment by coolrip007** [comment]
I DID WHAT RED PANDA SAID TO do hive-replace -y -s rAN THIS COM TO UPGARDE HIVEos TO 5.15 AND NIV DRIVE 525 

ANY THIS  else u need im here to HELP!!!!!! hope u are?    On Tuesday, April 11, 2023 at 04:16:32 PM CDT, Dennis Betts ***@***.***> wrote:  
 
  Sure just try it your self I discovered Your FLAW! just get an old mining rig u dont like and follow red pandda's vid on srb mioner and do his oc! but forget the c letter that sup to go --gpu-coffset 225 and out it --gpu-offset 225 so by mssing the letter c. it brun my psu! and i working to recreate like i did twice already! and film it ! becoz folks like u dont bleibve and seems like u will not even try it to SEE! so why email me? Im wokring with youtuber red panda and minesum101 and maybe son of tech my get me on the show and lets burn up some old mining rig! and it was the fuse that blow in the PSU! it toaste i tried to fix my by passing the fuse and its gone folks!//Mining cave psu quite 1,600 watts and man in 2 secs 2,000 watts hit so fast! i didnt have time to stop it! and it did it again but that time i had my hand on the power cord and saved that psu! so then i went over red panda vid again and saw i left the c out on the oc so i put that c in fornt like i missed and it mining great with dynex on srb miner! like really 1 letter missing can cause this to happen then i came across that dude vid below! and he has oc disclaimer! and said the same thing i starting saying be cafeful with OC and be safe ! 
red's How to mine Dynex, Radiant or Nexa in HiveOS.  

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
How to mine Dynex, Radiant or Nexa in HiveOS.


 |

 |

 |


How to mine Dynex, Radiant or Nexa in HiveOS.


thats BS ! i can redo too just leave the c off the setting --gpu-offset -225[11:59 PM]--gpu-cclock 1470--gpu-offset 225--gpu-mclock 5001--dynex-cpu-pow 0--disable-cpu-sync 1.195--mallob-endpoint http://mallob.neuropool.net:8081/[11:59 PM]now run THOSE settings in srb miner and watch your rig burn or fuse or break trip!  baby!
right is u look at line #2! where its <   --gpu-offset 225  > ??? what is missing is the letter c!!! should be --gpu-coffset 225!! not --gpu-offset 225! with the c letter missing your rig will  power like a light house man! i triple dare to try that! be  warned and ready to pull the power plug from the wall! bro  and your fans will spend so loud and fast like roaring sound  in about 3 secs your psu is toast! i was mining dynex in hive os  newest image with srb miner! Ill do a youtube vid to prove it!  i did recreate it twice!
recipe for burning rigs and homes if not careful! here i go talk to a non believer like its going to do any good coz u already believe what u want to believe without trying it and=d no proof!. well i have an old mining rig! and ill do a vid and post it on mu youtube channel Keith Savage (BJJ) . use that to fing it! youll see me old guy doing BJJ torments! i. so iT REAL AND WE ll I HAVE A NEW 1,600 PLAT EVGA psu!!! NICE! BUT I LOST A GREAT PSU $230 BUCKS DIOWN THE DRIAN BECOZ Y'ALL GUYS DONT HAVE any safe gurads! MOST THE TIME WHN I MISS UPA OC HIVE OS TELLS ME OR THE MINER JUST DONT WORK! BUT YOURS ON THE OTHER HAND! BURNS BROTHER !  
MUCH PEACE AND HOPE YA'LL FIX THIS ISSUE! IM NOT FOR ANY HAND OUTS JUST FIX IT ! 






i cant y'all u dont have any safe guards in your miner!!! even this dude said it happens to! BEST KASPA Overclock Settings Nicehash, Windows & HiveOS | 3060 3060Ti 3070 3070Ti 3080 3080Ti 3090 - YouTube

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
BEST KASPA Overclock Settings Nicehash, Windows & HiveOS | 3060 3060Ti 3...


 |

 |

 |




BEST KASPA Overclock Settings Nicehash, Windows & HiveOS | 3060 3060Ti 3070 3070Ti 3080 3080Ti 3090

said that i not put in the oc that miner will cause damage! and he has a disclaimer about the ocs! smart dude! 


    On Tuesday, April 11, 2023 at 11:48:15 AM CDT, uhliksk ***@***.***> wrote:  
 
 


I found interesting he's claiming to burn 1600 W PSU with 5x 240W 3070 GPUs running at 300W with total power surge of 2000W. I don't have a degree in mathematics but I feel something is wrong with this tale.

**Comment by coolrip007** [comment]
after i clock out from work ill use my cell and record it! and email that vid to you! around 7pm i should be done! and ill post it on my youtube and send you a copy!
    On Tuesday, April 11, 2023 at 04:40:09 PM CDT, Dennis Betts ***@***.***> wrote:  
 
  I DID WHAT RED PANDA SAID TO do hive-replace -y -s rAN THIS COM TO UPGARDE HIVEos TO 5.15 AND NIV DRIVE 525 

ANY THIS  else u need im here to HELP!!!!!! hope u are?    On Tuesday, April 11, 2023 at 04:16:32 PM CDT, Dennis Betts ***@***.***> wrote:  
 
  Sure just try it your self I discovered Your FLAW! just get an old mining rig u dont like and follow red pandda's vid on srb mioner and do his oc! but forget the c letter that sup to go --gpu-coffset 225 and out it --gpu-offset 225 so by mssing the letter c. it brun my psu! and i working to recreate like i did twice already! and film it ! becoz folks like u dont bleibve and seems like u will not even try it to SEE! so why email me? Im wokring with youtuber red panda and minesum101 and maybe son of tech my get me on the show and lets burn up some old mining rig! and it was the fuse that blow in the PSU! it toaste i tried to fix my by passing the fuse and its gone folks!//Mining cave psu quite 1,600 watts and man in 2 secs 2,000 watts hit so fast! i didnt have time to stop it! and it did it again but that time i had my hand on the power cord and saved that psu! so then i went over red panda vid again and saw i left the c out on the oc so i put that c in fornt like i missed and it mining great with dynex on srb miner! like really 1 letter missing can cause this to happen then i came across that dude vid below! and he has oc disclaimer! and said the same thing i starting saying be cafeful with OC and be safe ! 
red's How to mine Dynex, Radiant or Nexa in HiveOS.  

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
How to mine Dynex, Radiant or Nexa in HiveOS.


 |

 |

 |


How to mine Dynex, Radiant or Nexa in HiveOS.


thats BS ! i can redo too just leave the c off the setting --gpu-offset -225[11:59 PM]--gpu-cclock 1470--gpu-offset 225--gpu-mclock 5001--dynex-cpu-pow 0--disable-cpu-sync 1.195--mallob-endpoint http://mallob.neuropool.net:8081/[11:59 PM]now run THOSE settings in srb miner and watch your rig burn or fuse or break trip!  baby!
right is u look at line #2! where its <   --gpu-offset 225  > ??? what is missing is the letter c!!! should be --gpu-coffset 225!! not --gpu-offset 225! with the c letter missing your rig will  power like a light house man! i triple dare to try that! be  warned and ready to pull the power plug from the wall! bro  and your fans will spend so loud and fast like roaring sound  in about 3 secs your psu is toast! i was mining dynex in hive os  newest image with srb miner! Ill do a youtube vid to prove it!  i did recreate it twice!
recipe for burning rigs and homes if not careful! here i go talk to a non believer like its going to do any good coz u already believe what u want to believe without trying it and=d no proof!. well i have an old mining rig! and ill do a vid and post it on mu youtube channel Keith Savage (BJJ) . use that to fing it! youll see me old guy doing BJJ torments! i. so iT REAL AND WE ll I HAVE A NEW 1,600 PLAT EVGA psu!!! NICE! BUT I LOST A GREAT PSU $230 BUCKS DIOWN THE DRIAN BECOZ Y'ALL GUYS DONT HAVE any safe gurads! MOST THE TIME WHN I MISS UPA OC HIVE OS TELLS ME OR THE MINER JUST DONT WORK! BUT YOURS ON THE OTHER HAND! BURNS BROTHER !  
MUCH PEACE AND HOPE YA'LL FIX THIS ISSUE! IM NOT FOR ANY HAND OUTS JUST FIX IT ! 






i cant y'all u dont have any safe guards in your miner!!! even this dude said it happens to! BEST KASPA Overclock Settings Nicehash, Windows & HiveOS | 3060 3060Ti 3070 3070Ti 3080 3080Ti 3090 - YouTube

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
BEST KASPA Overclock Settings Nicehash, Windows & HiveOS | 3060 3060Ti 3...


 |

 |

 |




BEST KASPA Overclock Settings Nicehash, Windows & HiveOS | 3060 3060Ti 3070 3070Ti 3080 3080Ti 3090

said that i not put in the oc that miner will cause damage! and he has a disclaimer about the ocs! smart dude! 


    On Tuesday, April 11, 2023 at 11:48:15 AM CDT, uhliksk ***@***.***> wrote:  
 
 


I found interesting he's claiming to burn 1600 W PSU with 5x 240W 3070 GPUs running at 300W with total power surge of 2000W. I don't have a degree in mathematics but I feel something is wrong with this tale.

**Comment by coolrip007** [comment]
Come to my youtube channel keith savage bjj and ill do a vid and recrate that dangerous flaw

i should get paid for a bug finder fee! most software folks poay to have bugs reported not be treated with the 5th!

Keith Savage @hdcomputerkeith
https://www.youtube.com/channel/UCH5rT6dVrsJ2HxaNmzp4wzQ


Welcome to Savage Crypto Mining Channel! Thanks! :)
Been doing this crypto for 2 years now! Following crypto mining youtube
 channels learning how to mine crypto!!! 
and know both red fox and red panda real good at what they do
(BUT no OC disclaimers)
by: Red Panda Mining = @RedPandaMining
How to mine Dynex, Radiant or Nexa in HiveOS.
https://www.youtube.com/watch?v=blXnUM3rdgA&t=2s


hive-replace -y -s  (it upgraded to below versions)
5.15.0-hiveos #96 Kernel Version N525.89.02 RTX 3070 × 5 (each hit 300 watts max each burnt my 1,600 watt PSU up
 rig hit over 2,000 watts in 3 secs and fan roared at 100 % loud too)S! and after correction mined at 70 watts each)
thats BS ! i can recreate it over again too by just leave the c off the setting --gpu-offset -225
[11:59 PM]
--gpu-cclock 1470
--gpu-offset 225
--gpu-mclock 5001
--dynex-cpu-pow 0
--disable-cpu-sync 1.195
--mallob-endpoint http://mallob.neuropool.net:8081/
[11:59 PM]
now run THOSE settings in srb miner and watch your rig blow baby!

right is u look at line #2! where its <   --gpu-offset 225  > ??? 
what is missing is the letter c!!! should be --gpu-coffset 225!!
 not --gpu-offset 225! with the c letter missing your rig will 
 power like a light house man! i triple dare to try that! be 
 warned and ready to pull the power plug from the wall! bro 
 and your fans will spend so loud and fast like roaring sound 
 in about 3 secs your psu is toast! i was mining dynex in hive os 
 newest image with srb miner! Ill do a youtube vid to prove it! 
 i did recreate it twice!
 
 (Has a OC Disclaimer)go check it out and add one to yours)
by: Crypto Mining Insider = @CryptoMiningInsider
Overclock Settings Nicehash, Windows & HiveOS
https://www.youtube.com/watch?v=wcd7rTilIu4

I reach out to red panada chated with him and also minesum101 knows also
Just wnated the whole mining cum to know to be carefull with mining software 
like srb miner! rem I found the flaw and now exposing to the whole world via internet
now a balck hat hacker that already know how to hack miners hive os account
if the miner is useing srbminer they can target and burn their farms down!
Image about mil worth of mining hardware eq all get distory becoz of a flaw in srb miner! 
i know if i lost all mine i would so heart broken over losing that much money
U better belive i am coming to visit that dev that created and coded that crapy miner
poor code now days burning GPU when play BETA games like 3090s by amazon
and now 3080tis by playing D4! What is going on here where software are burning up hardware!!!! WTH
and this is really happening and this dude from their GITHUB emailed me still doubing me!
i emailed him all do a video! and SRB miner kicked me out of tier discord!
and thier github emailed my the name of! 

doktor83/SRBMiner-Multi uhliksk <notifications@github.com>
said below! i said HIVEOS rep[ort 2,000 w even that gpu in hive show max at 300W not 
240 x 5= 1,200w but they hit 300w each x 5= 1,500 and my psu was 1,600 w! well that right broke the 80% rule!!!
well so what if math is not correct to 100% ass whip the fact is it burnt MY PSU! and ill take a pic of it and post it here! 

I found interesting he's claiming to burn 1600 W PSU with 5x 240W 3070 GPUs 
running at 300W with total power surge of 2000W. I don't have a degree 
in mathematics ( nether do i but i didnt lie)  but I feel something is wrong with this tale. ( it really happen)
(you can see this dude is dumb becoz Niv GPU 3070 has 3 power ranges! 
right out of HIVE OS and he texted 240W now have said it can get to 300 W each and it did!
even at that dummy 240 x 5=
GPU 0
0c:00.0
GeForce RTX 3070 8192 MB · EVGA
Samsung GDDR6 · 94.04.46.40.7F · PL 100 W, 270 W, 300 W

what for a hacker to get ahold of this flaw and hack some hive os and switch the miner to srb and set the settings like i did and burn down mining farms like a big attack know that this info is posted on the internet the whole world we see this flaw!
plz set safe guards into the miner to prevent this from happing! 

so i have an old pc to show you! ill post the link when i get it down! 

Welcome to Savage Crypto Mining Channel! Thanks! :)
Been doing this crypto for 2 years now! Following crypto mining youtube
 channels learning how to mine crypto!!! 
and know both red fox and red panda real good at what they do
(BUT no OC disclaimers)
by: Red Panda Mining = @RedPandaMining
How to mine Dynex, Radiant or Nexa in HiveOS.
https://www.youtube.com/watch?v=blXnUM3rdgA&t=2s


hive-replace -y -s  (it upgraded to below versions)
5.15.0-hiveos #96 Kernel Version N525.89.02 RTX 3070 × 5 (each hit 300 watts max each burnt my 1,600 watt PSU up
 rig hit over 2,000 watts in 3 secs and fan roared at 100 % loud too)S! and after correction mined at 70 watts each)
thats BS ! i can recreate it over again too by just leave the c off the setting --gpu-offset -225
[11:59 PM]
--gpu-cclock 1470
--gpu-offset 225
--gpu-mclock 5001
--dynex-cpu-pow 0
--disable-cpu-sync 1.195
--mallob-endpoint http://mallob.neuropool.net:8081/
[11:59 PM]
now run THOSE settings in srb miner and watch your rig blow baby!

right is u look at line #2! where its <   --gpu-offset 225  > ??? 
what is missing is the letter c!!! should be --gpu-coffset 225!!
 not --gpu-offset 225! with the c letter missing your rig will 
 power like a light house man! i triple dare to try that! be 
 warned and ready to pull the power plug from the wall! bro 
 and your fans will spend so loud and fast like roaring sound 
 in about 3 secs your psu is toast! i was mining dynex in hive os 
 newest image with srb miner! Ill do a youtube vid to prove it! 
 i did recreate it twice!
 
 (Has a OC Disclaimer)go check it out and add one to yours)
by: Crypto Mining Insider = @CryptoMiningInsider
Overclock Settings Nicehash, Windows & HiveOS
https://www.youtube.com/watch?v=wcd7rTilIu4

I reach out to red panada chated with him and also minesum101 knows also
Just wnated the whole mining cum to know to be carefull with mining software 
like srb miner! rem I found the flaw and now exposing to the whole world via internet
now a balck hat hacker that already know how to hack miners hive os account
if the miner is useing srbminer they can target and burn their farms down!
Image about mil worth of mining hardware eq all get distory becoz of a flaw in srb miner! 
i know if i lost all mine i would so heart broken over losing that much money
U better belive i am coming to visit that dev that created and coded that crapy miner
poor code now days burning GPU when play BETA games like 3090s by amazon
and now 3080tis by playing D4! What is going on here where software are burning up hardware!!!! WTH
and this is really happening and this dude from their GITHUB emailed me still doubing me!
i emailed him all do a video! and SRB miner kicked me out of tier discord!
and thier github emailed my the name of! 

doktor83/SRBMiner-Multi uhliksk <notifications@github.com>
said below! i said HIVEOS rep[ort 2,000 w even that gpu in hive show max at 300W not 
240 x 5= 1,200w but they hit 300w each x 5= 1,500 and my psu was 1,600 w! well that right broke the 80% rule!!!
well so what if math is not correct to 100% ass whip the fact is it burnt MY PSU! and ill take a pic of it and post it here! 

I found interesting he's claiming to burn 1600 W PSU with 5x 240W 3070 GPUs 
running at 300W with total power surge of 2000W. I don't have a degree 
in mathematics but I feel something is wrong with this tale.
(you can see this dude is dumb becoz Niv GPU 3070 has 3 power ragnges! 
right out of HIVE OS and he texted 240W now have said it can get to 300 W each and it did!
even at that dummy 240 x 5=
GPU 0
0c:00.0
GeForce RTX 3070 8192 MB · EVGA
Samsung GDDR6 · 94.04.46.40.7F · PL 100 W, 270 W, 300 W

**Comment by coolrip007** [comment]
ok made the vid and im asking rabit mining to get all the miner to reach out to u srb miner for this fix! your flaw has all out hiveos mining rigs in danger! by not fixing this flaw! here the vid i made and uploaded to my youtube channel! I going to reach out to red panda and the others! https://youtu.be/GMgNDlq2hk8

**Comment by coolrip007** [comment]
theres your proof! https://youtu.be/GMgNDlq2hk8

**Comment by coolrip007** [comment]
Here's my proof srb miner . I discovered a very dangerous  flaw! miners How hacker can burn your mining farms down. SRB Miner refuse to build safe guards into the code!


| 
| 
| 
|  |  |

 |

 |
| 
|  | 
How hacker can burn your mining farms down. SRB Miner refuse to build sa...


 |

 |

 |



   On Tuesday, April 11, 2023 at 04:45:35 PM CDT, Dennis Betts ***@***.***> wrote:  
 
  after i clock out from work ill use my cell and record it! and email that vid to you! around 7pm i should be done! and ill post it on my youtube and send you a copy!
    On Tuesday, April 11, 2023 at 04:40:09 PM CDT, Dennis Betts ***@***.***> wrote:  
 
  I DID WHAT RED PANDA SAID TO do hive-replace -y -s rAN THIS COM TO UPGARDE HIVEos TO 5.15 AND NIV DRIVE 525 

ANY THIS  else u need im here to HELP!!!!!! hope u are?    On Tuesday, April 11, 2023 at 04:16:32 PM CDT, Dennis Betts ***@***.***> wrote:  
 
  Sure just try it your self I discovered Your FLAW! just get an old mining rig u dont like and follow red pandda's vid on srb mioner and do his oc! but forget the c letter that sup to go --gpu-coffset 225 and out it --gpu-offset 225 so by mssing the letter c. it brun my psu! and i working to recreate like i did twice already! and film it ! becoz folks like u dont bleibve and seems like u will not even try it to SEE! so why email me? Im wokring with youtuber red panda and minesum101 and maybe son of tech my get me on the show and lets burn up some old mining rig! and it was the fuse that blow in the PSU! it toaste i tried to fix my by passing the fuse and its gone folks!//Mining cave psu quite 1,600 watts and man in 2 secs 2,000 watts hit so fast! i didnt have time to stop it! and it did it again but that time i had my hand on the power cord and saved that psu! so then i went over red panda vid again and saw i left the c out on the oc so i put that c in fornt like i missed and it mining great with dynex on srb miner! like really 1 letter missing can cause this to happen then i came across that dude vid below! and he has oc disclaimer! and said the same thing i starting saying be cafeful with OC and be safe ! 
red's How to mine Dynex, Radiant or Nexa in HiveOS.  

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
How to mine Dynex, Radiant or Nexa in HiveOS.


 |

 |

 |


How to mine Dynex, Radiant or Nexa in HiveOS.


thats BS ! i can redo too just leave the c off the setting --gpu-offset -225[11:59 PM]--gpu-cclock 1470--gpu-offset 225--gpu-mclock 5001--dynex-cpu-pow 0--disable-cpu-sync 1.195--mallob-endpoint http://mallob.neuropool.net:8081/[11:59 PM]now run THOSE settings in srb miner and watch your rig burn or fuse or break trip!  baby!
right is u look at line #2! where its <   --gpu-offset 225  > ??? what is missing is the letter c!!! should be --gpu-coffset 225!! not --gpu-offset 225! with the c letter missing your rig will  power like a light house man! i triple dare to try that! be  warned and ready to pull the power plug from the wall! bro  and your fans will spend so loud and fast like roaring sound  in about 3 secs your psu is toast! i was mining dynex in hive os  newest image with srb miner! Ill do a youtube vid to prove it!  i did recreate it twice!
recipe for burning rigs and homes if not careful! here i go talk to a non believer like its going to do any good coz u already believe what u want to believe without trying it and=d no proof!. well i have an old mining rig! and ill do a vid and post it on mu youtube channel Keith Savage (BJJ) . use that to fing it! youll see me old guy doing BJJ torments! i. so iT REAL AND WE ll I HAVE A NEW 1,600 PLAT EVGA psu!!! NICE! BUT I LOST A GREAT PSU $230 BUCKS DIOWN THE DRIAN BECOZ Y'ALL GUYS DONT HAVE any safe gurads! MOST THE TIME WHN I MISS UPA OC HIVE OS TELLS ME OR THE MINER JUST DONT WORK! BUT YOURS ON THE OTHER HAND! BURNS BROTHER !  
MUCH PEACE AND HOPE YA'LL FIX THIS ISSUE! IM NOT FOR ANY HAND OUTS JUST FIX IT ! 






i cant y'all u dont have any safe guards in your miner!!! even this dude said it happens to! BEST KASPA Overclock Settings Nicehash, Windows & HiveOS | 3060 3060Ti 3070 3070Ti 3080 3080Ti 3090 - YouTube

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
BEST KASPA Overclock Settings Nicehash, Windows & HiveOS | 3060 3060Ti 3...


 |

 |

 |




BEST KASPA Overclock Settings Nicehash, Windows & HiveOS | 3060 3060Ti 3070 3070Ti 3080 3080Ti 3090

said that i not put in the oc that miner will cause damage! and he has a disclaimer about the ocs! smart dude! 


    On Tuesday, April 11, 2023 at 11:48:15 AM CDT, uhliksk ***@***.***> wrote:  
 
 


I found interesting he's claiming to burn 1600 W PSU with 5x 240W 3070 GPUs running at 300W with total power surge of 2000W. I don't have a degree in mathematics but I feel something is wrong with this tale.
