### ISSUE TITLE
Any chance in supporting ROCm for Linux?

### ISSUE THREAD

**Issue by ajboni** [doktor83/SRBMiner-Multi#23]
I get this with RX580 

`[2021-03-09 15:52:25] Old gpu/s detected, --gpu-auto-tune 2 is advised to find optimal settings
[2021-03-09 15:52:26] No binary found for GPU0
[2021-03-09 15:52:26] No binary found for GPU0
`

**Comment by doktor83** [comment]
Not at the moment

**Comment by DeeDeeRanged** [comment]
Actually you don't need rocm, just legacy. I am running Debian bullseye/testing with the latest official kernel 5.10.0-6 an rx 580. As I am using the latest kernel cannot install the amdgpu 20.50 as you need an older kernel. There is a workaround install the opencl drivers as follows.
Unpack the amdgpu driver cd into where you unpacked the driver run amdgpu-install --opencl=legacy --headless --no-dkms. rx 580 is not a rocm card.

**Comment by ajboni** [comment]
> Actually you don't need rocm, just legacy. I am running Debian bullseye/testing with the latest official kernel 5.10.0-6 an rx 580. As I am using the latest kernel cannot install the amdgpu 20.50 as you need an older kernel. There is a workaround install the opencl drivers as follows.
> Unpack the amdgpu driver cd into where you unpacked the driver run amdgpu-install --opencl=legacy --headless --no-dkms. rx 580 is not a rocm card.

Yes, eventually it stopped working for me after rocm 3 or something. Used this snippet iirc, its working great so far. Thanks for the input.,

https://gist.github.com/kytulendu/3351b5d0b4f947e19df36b1ea3c95cbe

**Comment by DeeDeeRanged** [comment]
Since yesterday I got a r9 390 8gb and that one performs quite a bit better than my rx 580. 30+ MH/s vs 26 MH/s ethash
