### ISSUE TITLE
Error sha256dt mining "Novo"

### ISSUE THREAD

**Issue by marlongb** [doktor83/SRBMiner-Multi#233]
![Captura de tela de 2023-04-09 22-12-33](https://user-images.githubusercontent.com/12714525/230806462-2700edc5-7dc3-41ad-b55f-d20b926b0106.png)

**Comment by doktor83** [comment]
what is your nvidia driver version?

**Comment by marlongb** [comment]
525.89.02
![Captura de tela de 2023-04-11 22-04-25](https://user-images.githubusercontent.com/12714525/231320732-e39e9031-f9b8-4fa4-af21-03b4b6db3ad4.png)

**Comment by marlongb** [comment]
I uninstalled all hiveOS miners and installed again, it worked.
Thanks
