### ISSUE TITLE
Add SHA3d for Nvidia

### ISSUE THREAD

**Issue by JayBitron** [doktor83/SRBMiner-Multi#237]
Hello,

Thanks for supporting the algo in https://github.com/doktor83/SRBMiner-Multi/issues/107
Kylacoin is the only active coin with this algo,
Users are asking for Nivida support as well,
and also for old AMD GPU like R9 390

Thanks!

**Comment by doktor83** [comment]
Nvidia will be added in next release but AMD gpus older than rx470 wont be supported.
