### ISSUE TITLE
Almost 2 times lower hashrate than OneZeroMiner on rtx3090

### ISSUE THREAD

**Issue by sosme2012** [doktor83/SRBMiner-Multi#242]
RTX3090.  the same overclocking settings.
OneZeroMiner v1.0.3 got 5.2 KH/s
SRBMiner-MULTI v2.2.4 got 2.7 KH/s

RTX3080.  the same overclocking settings.
OneZeroMiner v1.0.3 got 3.2 KH/s
SRBMiner-MULTI v2.2.4 got 2.2 KH/s

![1](https://user-images.githubusercontent.com/90928649/232011614-d3f6d0ec-79aa-40fc-9ea0-e5b609dd8434.JPG)
![2](https://user-images.githubusercontent.com/90928649/232011625-391b8eff-8a21-4d6d-b0fe-ddf4d5ea0849.JPG)

I have been using srbminer and don't want to switch to other software. I hope it can be upgraded. Thank you.

**Comment by doktor83** [comment]
Thats because you need to manually set lower --gpu-intensity value.
Join dynex discord and find right values for your gpus
