### ISSUE TITLE
Can't change worker name, no hashrate in pool

### ISSUE THREAD

**Issue by robertus2208** [doktor83/SRBMiner-Multi#246]
--worker doesnt change name and if i have more than one rigs mining on same pool and wallet my hashrate is invisible on pool (0 hashrate) on second miner. 
What im doing wrong?is --worker (worker name here) right? If i have two workers without name then second worker has 0 hashrate on pool.

**Comment by dodther** [comment]
Rig Name can only enter field the password.
https://ekapool.com/dnx/#getting_started

**Comment by robertus2208** [comment]
In windows not hive

**Comment by doktor83** [comment]
password field, who said hiveos ? **--password your-worker-name-here**
