### ISSUE TITLE
Miner don't work at all (RXD)

### ISSUE THREAD

**Issue by mRnEeB** [doktor83/SRBMiner-Multi#248]
When I start miner, it recognizes all my graphics cards, but nothing happens and mine does not start.
I read somewhere that it might be a connection problem, but it doesn't show anything.
Is there a solution?

**Comment by zuolirui** [comment]
I am also in the same situation on RXD

**Comment by mRnEeB** [comment]
> I am also in the same situation on RXD

yes it's about Radiant(RXD)

**Comment by doktor83** [comment]
use ver 2.2.3 or wait for 2.2.5.
