### ISSUE TITLE
OC's not applying?

### ISSUE THREAD

**Issue by nicbtc** [doktor83/SRBMiner-Multi#249]
Hi! I am trying to apply OC's for my cards but they are not applied

I get this error [https://i.imgur.com/k0a9NUI.png](url)

And I am using this lines in code

--gpu-id 3,4,5,7,8,12
--gpu-cclock0 1500,1500,1500,1500,1500,1500
--gpu-mclock0 5000,5000,5000,5000,5000,5000

Thanks in advance

**Comment by nicbtc** [comment]
I guess so, I am runing it hiveos.

**Comment by doktor83** [comment]
--gpu-mclock0 5001,5001,5001,5001,5001,5001

maybe?
