### ISSUE TITLE
One card out of two does not work.

### ISSUE THREAD

**Issue by Atceton** [doktor83/SRBMiner-Multi#25]
There are two cards installed on the PC, in the pciex16 (bus 01) connector - rx480, in the pciex1 -rx570 connector. Driver version 20.2.3. Problem - one card always works - rx 570, rx470 is idle. Nothing helps.

**Comment by doktor83** [comment]
paste --list-devices here

**Comment by Atceton** [comment]
Detected GPU devices

GPU0  [0] [01:00.0] : radeon__tm__rx_480_graphics [ellesmere] [8192 MB] [CU: 36] [MB: 7936 MB] [MID: 5] [CID: 2]
GPU1  [0] [04:00.0] : radeon_rx_570_series [ellesmere] [8192 MB] [CU: 32] [MB: 7936 MB] [MID: 4] [CID: 2]

**Comment by Atceton** [comment]
![1](https://user-images.githubusercontent.com/48236868/111951220-2e21da80-8b05-11eb-88ac-aaf53b69a2bb.png)

**Comment by doktor83** [comment]
ok, so it is zil+eth. have you tried it with another algorithm ?

**Comment by Atceton** [comment]
In other algorithms, video cards work fine. 
BAT-file:

setx GPU_MAX_HEAP_SIZE 100	
setx GPU_MAX_USE_SYNC_OBJECTS 1	
setx GPU_SINGLE_ALLOC_PERCENT 100	
setx GPU_MAX_ALLOC_PERCENT 100	
setx GPU_MAX_SINGLE_ALLOC_PERCENT 100	
setx GPU_ENABLE_LARGE_ALLOCATION 100
setx GPU_MAX_WORKGROUP_SIZE 1024

@echo off
cd %~dp0
cls

SRBMiner-MULTI.exe --disable-cpu --multi-algorithm-job-mode 3 --a0-is-zil --algorithm ethash;ethash --pool eu.ezil.me:5555;eu.ezil.me:5555 --wallet 0xxxx.zilxxx;0xxxx.zilxxx --worker rx570-zil;rx570-eth --gpu-boost 3;0

pause

**Comment by doktor83** [comment]
tested on one of my rigs and it works fine. try :

**SRBMiner-MULTI.exe --disable-cpu --disable-workers-ramp-up --multi-algorithm-job-mode 3 --a0-is-zil --algorithm ethash;ethash --gpu-id 0!1;0!1 --pool eu.ezil.me:5555;eu.ezil.me:5555 --wallet 0xxxx.zilxxx;0xxxx.zilxxx --worker zil;eth --gpu-boost 3;0**

**Comment by Atceton** [comment]
Thank you so much! It works great! Your program is the best of all.
