### ISSUE TITLE
Alephium WP pool hashrate is third of SRB hashrate.

### ISSUE THREAD

**Issue by mmeeffllff** [doktor83/SRBMiner-Multi#256]
OS Windows 10
Cards : 3x RX570 (OC : core 2050 MHz, mem 1000MHz, Vcore=900mV)
pool : woolypooly
SRBMiner version 2.2.4 (already seen on previous versions)

Any attempt to mine alephium on woolypooly with my polaris rig results in less than a third of the hashrate to get to the pool. 
SRBMiner : 1250 MH/s
WoolyPooly : ~320 MH/s
I've already seen this during double mining with ETC on previous versions, and other AMD cards (Navi2).
Don't know if it is pool specific or not.

**Comment by doktor83** [comment]
you would know if you try on a different pool. Herominers, P1pool no issues. I know about the wooly issue, but never cared enough to contact them.

**Comment by mmeeffllff** [comment]
Hi, seems like you did the job after all!
Thank you.
