### ISSUE TITLE
First gpu-intensity value applied to all GPU - Windows 2.2.5

### ISSUE THREAD

**Issue by spleen911** [doktor83/SRBMiner-Multi#257]
I have a mix of 1080/1660/2060 and want to use multiple intensity for highest hashrate.

`--algorithm dynex --gpu-intensity 320,320,224,224,288,288`

![image](https://user-images.githubusercontent.com/68015090/235356993-030e6764-32a1-45a6-af6d-93b3c1d3b4c5.png)

**Comment by doktor83** [comment]
--gpu-id 0,1,2,3,4,5
