### ISSUE TITLE
2.2.5 dual dynex is broken on amd 4G

### ISSUE THREAD

**Issue by Quake4** [doktor83/SRBMiner-Multi#260]
225:
![srbm](https://user-images.githubusercontent.com/29517243/235623462-91c35244-ffcb-41b8-a26b-5b48fd2b133a.png)

224
![srbm2](https://user-images.githubusercontent.com/29517243/235623512-0cfda826-271f-4d51-ab83-6abbc54e0479.png)

**Comment by doktor83** [comment]
1. Empty cache folder
2. Download in cache folder : https://raw.githubusercontent.com/dynexcoin/dynexjobs/main/dynex_compute_w340.cnf
3. Enjoy
