### ISSUE TITLE
2.2.5 throws error -30

### ISSUE THREAD

**Issue by Mortuus-Medicus** [doktor83/SRBMiner-Multi#261]
![image](https://user-images.githubusercontent.com/10358658/235715375-81307347-80ed-471d-b61a-01ac90fff9ef.png)

I had no issue running 2.2.4 and am running it right now since 2.2.5 throws an error. 
All I did was download the new version, edit the config file to have my wallet address and password. 
But it just doesn't work....

**Comment by doktor83** [comment]
check https://github.com/doktor83/SRBMiner-Multi/issues/260
