### ISSUE TITLE
--gpu-mclock0 doesnt set the value

### ISSUE THREAD

**Issue by SilvesTIR** [doktor83/SRBMiner-Multi#266]
All overclock values set without issues but --gpu-mclock0 doesnt. It just resets the current value to zero. 

--gpu-mclock0 5001 seems to work in miner without any error. But value is still zero.

Im using up to date Hiveos with SRB Miner custom

**Comment by doktor83** [comment]
You forgot to write which GPU's are you talking about

**Comment by SilvesTIR** [comment]
RXT3060 and 3060ti series. None of them get the correct memory clock. 
If i set mem clock with vntool and start the miner, miner resets mem overclock value to zero.

**Comment by doktor83** [comment]
Well for start, memclock can't be set to 0. It can be reset to default value, but its value is never zero. So im not sure i understand your issue. Tested on hiveos and 3070ti, works as expected.

**Comment by SilvesTIR** [comment]
Sure, i mean nvtool reports as zero

HiveOS Nvtool 1.8.0
DEVICE #0:
  GPU CLOCKS LOCKED:  1650 MHz
  MEM CLOCKS LOCKED:       0 MHz
DEVICE #1:
  GPU CLOCKS LOCKED:  1650 MHz
  MEM CLOCKS LOCKED:       0 MHz
DEVICE #2:
  GPU CLOCKS LOCKED:  1650 MHz
  MEM CLOCKS LOCKED:       0 MHz
DEVICE #3:
  GPU CLOCKS LOCKED:  1650 MHz
  MEM CLOCKS LOCKED:       0 MHz

**Comment by SilvesTIR** [comment]
![1](https://user-images.githubusercontent.com/132595164/236614603-05343208-e909-4538-8447-ca8462332d15.jpg)
![2](https://user-images.githubusercontent.com/132595164/236614607-0a4b51a8-8d4d-4092-9415-ec4196a94257.jpg)
