### ISSUE TITLE
Start from a low --gpu-intensity value and see if it works

### ISSUE THREAD

**Issue by azharali121** [doktor83/SRBMiner-Multi#267]
Start from a low --gpu-intensity value and see if it works

_Originally posted by @doktor83 in https://github.com/doktor83/SRBMiner-Multi/issues/265#issuecomment-1533811397_
 Hi I have applied gpu intensity 2 but having hash rate on single card 86H in 2.4v having 870H.

**Comment by doktor83** [comment]
why 2 ? set it to minimum 256 then increase until hashrate starts to decline.

**Comment by azharali121** [comment]
Hi now working fine. Thanks
