### ISSUE TITLE
Hashrate increase at random followed by miner crash in Ergo

### ISSUE THREAD

**Issue by Ederson1993** [doktor83/SRBMiner-Multi#27]
Hello, I have a rig of 6 rx570 to mine ergo in srbMiner 0.7.1 where each plate makes an average of 70mhs. During yesterday the hashrate rose to 100mhs at random on all plates for about 20 minutes and then the miner crashed with the following error "Error -52 [clEnqueueNDRangeKernel [1]] [[BUS: 02] (Thread 2 )] ". this error appeared for each bus and thread.
[chart.pdf](https://github.com/doktor83/SRBMiner-Multi/files/6216267/chart.pdf)
![ergo hash](https://user-images.githubusercontent.com/25564344/112732530-6b85ce00-8f32-11eb-90be-837ec2c78073.png)

**Comment by Ederson1993** [comment]
Update: 
![imagem](https://user-images.githubusercontent.com/25564344/112733700-65472000-8f39-11eb-8c85-74a759032a4e.png)

**Comment by doktor83** [comment]
video driver crashed, nothing I can do about. if you have a lot of crashes like this, try using 1 thread per gpu (default is using 2)

**Comment by kusayuzayushko** [comment]
> video driver crashed, nothing I can do about. if you have a lot of crashes like this, try using 1 thread per gpu (default is using 2)

I can't find any info on how to set the number of GPU threads. Could you please add this info to the `./SRBMiner-MULTI --help` output?
