### ISSUE TITLE
Stuck miner at start hiveos?

### ISSUE THREAD

**Issue by pendoturbina** [doktor83/SRBMiner-Multi#276]
![image](https://github.com/doktor83/SRBMiner-Multi/assets/133072563/07997e7d-5809-4485-b28c-20a64ee3ac30)
![image](https://github.com/doktor83/SRBMiner-Multi/assets/133072563/c8c403de-6ed5-414f-9b8b-369fbb2e6276)

**Comment by doktor83** [comment]
it could be anything, but it was probably a crashed driver. you did restart your machine and try again before posting this ?

**Comment by doktor83** [comment]
many are running the custom miner on Hiveos without issues, so ill be honest - no idea. Try latest v.2.2.7
