### ISSUE TITLE
Need help we this command start.

### ISSUE THREAD

**Issue by BlackcatMotsu** [doktor83/SRBMiner-Multi#279]
Need help fixing this commend starter for etc kaspa and zil.  Yes, the wallet address is modified on this start-up commend but the problem is with the pool connection. Thank you to help me find a good start-up command.

:: This is an example you can edit and use
:: There are numerous parameters you can set, please check Help and Examples folder
:: Start miner with administrator privileges to enable gpu-boost

<job id="Elevate"><script language="VBScript">
  Set objShell = CreateObject("Shell.Application")
  Set objWshShell = WScript.CreateObject("WScript.Shell")
  Set objWshProcessEnv = objWshShell.Environment("PROCESS")
  strCommandLine = Trim(objWshProcessEnv("ELEVATE_CMDLINE"))
  objShell.ShellExecute "cmd", "/c " & strCommandLine, "", "runas"
</script></job>
:admin -----------------------------------------------------------

setx GPU_MAX_HEAP_SIZE 100
setx GPU_MAX_USE_SYNC_OBJECTS 1
setx GPU_SINGLE_ALLOC_PERCENT 100
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_MAX_SINGLE_ALLOC_PERCENT 100

SRBMiner-MULTI.exe --algorithm etchash --algorithm kaspa --zil-enable --pool etc-us-east1.nanopool.org:10100 --pool us1.kaspa-pool.org:4444 --zil-pool us-zil.shardpool.io:3333 --wallet 0xf59b3f309baCaC03410019f89eA0bfc028eXXXXX.010 --wallet Kaspa:qrtaf4zszuusaeer2fj9yuxmn44ppgzae5ktumnf9huaw6yy7pgv5wkfXXXXX.010 --zil-wallet zil1ugm4ytx4l8ueymghpu46ruheczmjzurxaXXXXX.010 --zil-esm 2
pause

**Comment by doktor83** [comment]
and what's the error you are getting? Cause the config looks ok

**Comment by BlackcatMotsu** [comment]
I get connection errors on Kaspa and zil. 

![image](https://github.com/doktor83/SRBMiner-Multi/assets/134010094/fa78d78f-ee99-4f9f-baa1-31d64e1d9794)

**Comment by BlackcatMotsu** [comment]
They do connect if I use lolmin...  software but I like more SRBminer. I use SRBminer for Raven and zil  and work well I like to try Tripple now

**Comment by doktor83** [comment]
first add --disable-cpu. now you can see it cant connect to the pool. i didnt check if you used right host:ip. if you do then maybe a firewall on the machine is blocking the connections

**Comment by doktor83** [comment]
also i guess you are not using the right format for shardpool

**Comment by BlackcatMotsu** [comment]
I did try the --disable-cpu but no change the ethc do connect so it not the firewall. I change the shardpool for: stratum+tcp://us2-zil.shardpool.io:3333  and now it connects. Thank you for the tip. I am all good now.
