### ISSUE TITLE
quoted passwords

### ISSUE THREAD

**Issue by DiscoTim** [doktor83/SRBMiner-Multi#28]
using quotes in the command line doesn't work.

eg.

--password "password=test"

without quotes srb will interpret that as trying to provide 2 passwords.

**Comment by doktor83** [comment]
yes, you can't use quotes. What are you trying to achieve here?

**Comment by DiscoTim** [comment]
we use the password field to pass some variables to the pool. it does work on all other miners.

**Comment by doktor83** [comment]
I was wrong:

**--password "password=test"** gets sent ok to the pool

"id":2,"jsonrpc":"2.0","method":"mining.authorize","params":["wallet","password=test"]

**Comment by DiscoTim** [comment]
i apologize if this is a mistake, it make have to do with the application the miner was using.
![screen2](https://user-images.githubusercontent.com/20764373/115110196-31638700-9f48-11eb-8c2f-6a69edc2b857.png)
![screen1](https://user-images.githubusercontent.com/20764373/115110197-31638700-9f48-11eb-9647-59d6fa996d49.png)

**Comment by doktor83** [comment]
the problem here is the **;** character, because it's used in SRBMiner as a separator for algorithms.
And after i checked on https://trtl.mine2gether.com/#getting_started they also want you to use **;** as a separator in the password field.
There is no workaround for this unless they change the separator :)

**Comment by DiscoTim** [comment]
It would seem to me that srb is not handling quotes properly. are you saying that a person can't use a ; in their password as well?
