### ISSUE TITLE
improve 2080 ti (slow) vs onz.

### ISSUE THREAD

**Issue by strannik357753** [doktor83/SRBMiner-Multi#284]
improve 2080 ti (slow) vs onz.
I think this is a problem with the 20x generation, since everything is fine at 30x
2080ti is slower than 1080ti

**Comment by strannik357753** [comment]
![onz](https://github.com/doktor83/SRBMiner-Multi/assets/60912947/fa60fcc6-1138-4c9c-9bf8-606e2338e0e8)
onz 
srb 
![srb](https://github.com/doktor83/SRBMiner-Multi/assets/60912947/273c5b97-7dcf-4d7c-a3a8-40b2c2e99ec6)

**Comment by VDV777** [comment]
Author doesn't answer, only close themes(

**Comment by doktor83** [comment]
Because i cant answer you "hey ok, now that you wrote it i will do it."
