### ISSUE TITLE
How to mine PEPA POW on CPU? 

### ISSUE THREAD

**Issue by spu-xb01** [doktor83/SRBMiner-Multi#285]
bat file closes on startup
and nothing happens, need additional options?

SRBMiner-MULTI.exe  --disable-gpu --algorithm memehash --pool stratum+tcp://fi.mining4people.com:4176 --wallet 8888

![image](https://github.com/doktor83/SRBMiner-Multi/assets/61787893/ab95b539-1d88-4f59-a956-2fd0db4c8a33)

**Comment by DJLazerjet** [comment]
I have the same problem.

**Comment by doktor83** [comment]
Miner crashes. I cant see the reason. And no point in mining with CPU.
