### ISSUE TITLE
i cannot verify on your discord

### ISSUE THREAD

**Issue by DJLazerjet** [doktor83/SRBMiner-Multi#286]
After 10 minutes of muting, discord kicks me from the channel.

**Comment by doktor83** [comment]
just write **/verify**

**Comment by DJLazerjet** [comment]
I simply do not have time to enter this command, because I am kicked out of the chat after 10 minutes, for which the discord mutes me. Second in second.

**Comment by DJLazerjet** [comment]
![изображение](https://github.com/doktor83/SRBMiner-Multi/assets/46873002/d786296d-5cd7-46b8-a8a9-86cb3f47fa4d)
