### ISSUE TITLE
naughty5?

### ISSUE THREAD

**Issue by laferri** [doktor83/SRBMiner-Multi#288]
![image](https://github.com/doktor83/SRBMiner-Multi/assets/76864828/20db9590-aecc-43e2-9245-cd456dad5034)
somebody help?

**Comment by doktor83** [comment]
remove windivert service

**Comment by SilentWarrior1** [comment]
you're my savior. I almost abandon in trying to make this miner work, and decided to go to the issues section.  

> remove windivert service

**Comment by laferri** [comment]
perfectly solved
