### ISSUE TITLE
How disable compute mode

### ISSUE THREAD

**Issue by sergeeximius** [doktor83/SRBMiner-Multi#29]
I turned on the GPU computing mode. How do I return to the original settings? How do I turn it off?
This line is not available in the driver settings gui (21.3.2)

**Comment by doktor83** [comment]
Use amd-compute-switcher tool

**Comment by sergeeximius** [comment]
I tried this utility. But there is only the on mode. I found information about the registry keys that are responsible for the compute mode. But it is not convenient that you can turn it on from the software, and to turn it off you have to look for a solution
