### ISSUE TITLE
--gpu-intensity

### ISSUE THREAD

**Issue by DeeDeeRanged** [doktor83/SRBMiner-Multi#36]
Debian bullseye/testing rx580 8GB
How do I have to interprid --gpu-intensity, in logfile I have this line:
A0|GPU0 | [BUS:0b] [I:         22] does that mean it is running --gpu-intensity 22?
Also noteced difference when I run --gpu-auto-tune 2 I see in the logfile
--gpu-intensity 8104640
Which should I use as it is not very clear in the help files or examples, unless I am missing something completely

**Comment by doktor83** [comment]
--gpu-intensity sets the number of threads that run on the GPU. 

if using 0-31, then in reality it is ( 1 << num ), but anything above 31 is treated as 'raw-intensity'.

This is not an issue, so i will close it.
