### ISSUE TITLE
ERGO CPU only mining error : CPU result rejected [didn't subscribe] [autolykos2][0]

### ISSUE THREAD

**Issue by Grouickman** [doktor83/SRBMiner-Multi#40]
Hello There,

I'm running 0.7.3.0 for mining ERGO with CPU only and it regularly run into this error after a while:
CPU result rejected [didn't subscribe] [autolykos2][0]

It mine properly for some times, encounter this error but seem to switch to a new block and then loop on this error.

logs are here : https://pastebin.com/24VCkxCk

The command line to start the miner (removed my wallet and rigname):
SRBMiner-MULTI.exe --algorithm autolykos2 --pool ergo.herominers.com:10250 --wallet xxxxxxxxxx --password xxxxxx

Edit: I tested on another computer and have the exact same issue.

**Comment by doktor83** [comment]
this is not a log, this is a copy paste of the console screen. Enable extended logging :

SRBMiner-MULTI.exe --algorithm autolykos2 --pool ergo.herominers.com:10250 --wallet xxxxxxxxxx --password xxxxxx --log-file ergolog.txt --extended-log

**Comment by Grouickman** [comment]
> this is not a log, this is a copy paste of the console screen. Enable extended logging :
> 
> SRBMiner-MULTI.exe --algorithm autolykos2 --pool ergo.herominers.com:10250 --wallet xxxxxxxxxx --password xxxxxx --log-file ergolog.txt --extended-log

My bad, did not knew there was a log option.

Logs are here :https://pastebin.com/znHmPYwE
error starting line#266

**Comment by doktor83** [comment]
people with low hash power also experience same thing on herominers pool. have you tried on a different pool?

**Comment by doktor83** [comment]
confirmed by herominers pool owner. You can try to set static difficulty and see if that helps.
