### ISSUE TITLE
Crashing with —gpu-auto-tune and lower hash rate with 0.7.5

### ISSUE THREAD

**Issue by jbright2** [doktor83/SRBMiner-Multi#41]
Just downloaded version 0.7.5, miner is crashing when —gpu auto-tune is turned on, when off hash rate is lower than in 0.7.3 (39 mh/s vs ~43 in 0.7.3)

mining ergo with r9 380, any help appreciated.

thanks.

**Comment by doktor83** [comment]
yeah i got reports for lower hr on tongas, next release will fix it
