### ISSUE TITLE
No worker devices?

### ISSUE THREAD

**Issue by nefilim** [doktor83/SRBMiner-Multi#42]
Ubuntu 20.04.2 LTS, using amdgpu-pro-20.50-1234664-ubuntu-20.04 drivers. 

> ~/SRBMiner-Multi-0-7-5# ./start-mining-ergo.sh 
> Detecting OpenCL devices...
> 
> GPU0 : vega_10_xl/xt__radeon_rx_vega_56/64_  [gfx900       ][MEM:  8176 MB][CU: 64][BUS: 03]
> GPU1 : vega_20__radeon_vii_                  [gfx906       ][MEM: 16368 MB][CU: 60][BUS: 06]
> 
> ======================================================================
> SRBMiner-MULTI 0.7.5
> 
> Press 's' to display stats
> Press 'h' to display hashrate
> Press 'p' to switch to the next pool
> Press 'o' to switch to the previous pool
> Press 0-9 to disable/enable GPU 0-9, shift+0-9 for GPU 10-19
> Press + or - to change gpu boost value
> ======================================================================
> 
> Algorithm/s         : autolykos2 [2.00% fee]
> Gpu mining          : enabled
> Cpu mining          : disabled
> Gpu tweaking        : enabled
> Gpu watchdog        : enabled
> 
> [2021-05-18 14:15:53] If you experience crashes on 'autolykos2' algorithm, try using 1 thread per GPU ( --gpu-intensity 0 )
> [2021-05-18 14:15:55] No worker devices found
>

**Comment by doktor83** [comment]
installed driver with pal, legacy ?

**Comment by miner59er** [comment]
I also have this result on:
3.16.0-6-amd64 #1 SMP Debian 3.16.56-1+deb8u1 (2018-05-08) x86_64 GNU/Linux 
using AMD-Catalyst-15.9
It gives this result:
` Detecting OpenCL devices...

CPU0 : Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz [L3:   6144 KB][L2:  1024 KB][L1:  128 KB][PU:   4]
GPU0 : amd_radeon_r9_200_series              [hawaii       ][MEM:  4004 MB][CU: 40][BUS: 01]

======================================================================
SRBMiner-MULTI 0.8.9

Press 's' to display stats
Press 'h' to display hashrate
Press 'p' to switch to the next pool
Press 'o' to switch to the previous pool
Press 0-9 to disable/enable GPU 0-9, shift+0-9 for GPU 10-19
======================================================================

Algorithm/s         : etchash [0.65% fee]
Gpu mining          : enabled
Cpu mining          : enabled
Watchdog            : enabled
Gpu tweaking        : disabled
Huge-pages          : available
HW-Aes              : available

[2022-02-03 18:01:52] Old gpu detected, --gpu-auto-tune 2 is advised to find optimal settings
[2022-02-03 18:01:52] Please run miner as administrator/root to enable GPU tweaking
[2022-02-03 18:01:52] Run miner with root privileges to enable MSR tweaks
[2022-02-03 18:01:52] Algorithm 0 available values for --cpu-threads-intensity : 1
[2022-02-03 18:01:53] No worker devices found`
