### ISSUE TITLE
"You defined more passwords than algorithms"

### ISSUE THREAD

**Issue by DarkVoyage** [doktor83/SRBMiner-Multi#43]
Hello. The pool requires to send parameters inside password and the string contains semicolons, which makes it impossible to send, because semicolon is used by SRBMiner itself as delimiter of algos. Tried different escape character variants, nothing works.

Example of what required:
send this as "password" > **w=_worker_name_;pass=_password_;d=_difficulty_**
semicolon inside string is needed to delimit the parameters

1. Can you add some escape character to send semicolon? For example, "  **;;**  " or "  **\\;**  ".
2. Add multi-algo possibility in config file. This will make Restarter less needed. Miner .exe can be kept alive with more common methods.

Regards.

**Comment by doktor83** [comment]
yeah, i should add an escape character for ; and ! which are used by miner as delimiters. 
Regarding config file, its deprecated, i don't want to work on it anymore.
