### ISSUE TITLE
Web GUI easy to ready

### ISSUE THREAD

**Issue by wthubhub** [doktor83/SRBMiner-Multi#44]
Hi, just ask any idea how make web gui more easy to ready? (adding bar or graph display)

thanks

**Comment by doktor83** [comment]
what?

**Comment by wthubhub** [comment]
hi before u use nanomier they have web gui like this
![image](https://user-images.githubusercontent.com/33279218/119930786-510bb780-bfaa-11eb-93d4-2c5dfa612260.png)

is it possible SRBMiner have same web gui like that?
i already set API remote enable the result is static report, 

{
    "rig_name": "192.168.3.71",
    "miner_version": "0.7.3",
    "driver_version": "27.20.1034.6",
    "mining_time": 15459,
    "total_cpu_workers": 7,
    "total_gpu_workers": 4,
    "total_workers": 11,
    "cpu_devices": [
        {
            "id": 0,
            "device": "cpu0",
            "model": "Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz",
            "L3": 8388608,
            "L2": 1048576,
            "L1": 131072
        }
    ],
    "gpu_devices": [
        {
            "id": 0,
            "bus_id": 1,
            "device": "gpu0",
            "model": "radeon_rx_570_series",
            "core_clock": 1250,
            "memory_clock": 1950,
            "temperature": 58,
            "fan_speed_rpm": 2336,
            "compute_errors": 0
        },
        {
            "id": 1,
            "bus_id": 3,
            "device": "gpu1",
            "model": "radeon_rx_570_series",
            "core_clock": 1320,
            "memory_clock": 2020,
            "temperature": 67,
            "fan_speed_rpm": 1868,
            "compute_errors": 0
        }
    ],
    "algorithms": [
        {
            "id": 0,
            "name": "verushash",
            "pool": {
                "pool": "ap.luckpool.net:3957",
                "time_connected": "2021-05-28 07:30:06",
                "uptime": 15457,
                "difficulty": 0.0062693592,
                "last_job_received": 17,
                "latency": 17
            },
            "shares": {
                "total": 3981,
                "accepted": 3974,
                "rejected": 7,
                "avg_find_time": 3
            },
            "hashrate": {
                "now": 7272836.078295595,
                "1min": 7132500.617885003,
                "5min": 7271046.848914431,
                "30min": 7262455.780184444,
                "max": 7558549.365345786,
                "cpu": {
                    "thread0": 1034988.9749168368,
                    "thread1": 1046286.7247652912,
                    "thread2": 1043249.2339317772,
                    "thread3": 1039842.9718728685,
                    "thread4": 1038905.4553131422,
                    "thread5": 1037628.1095030231,
                    "thread6": 1031934.6079926556,

**Comment by doktor83** [comment]
try **http://127.0.0.1:21550/stats**

**Comment by wthubhub** [comment]
ok nice 
now easy to ready thanks alot

![image](https://user-images.githubusercontent.com/33279218/120057793-30a63080-c070-11eb-9610-e2a4bdb4dde3.png)
