### ISSUE TITLE
Nvidia card support

### ISSUE THREAD

**Issue by A-z-z-y** [doktor83/SRBMiner-Multi#48]
Hello! I know that you normally immediately close issues like this, but to be clear, all Nvidia cards after the GTX 260 support opencl, so I am unable to understand why the miner wouldn't work with Nvidia cards. Is there a way to make it work with Nvidia cards, or is there some issue with this that i'm overlooking? Thanks, and have a great day!

**Comment by doktor83** [comment]
Right, i close issues like this cause it's not an issue. ATM i am not going to invest time and energy into learning about Nvidia architecture, CUDA, etc. But i won't say never, who knows.

**Comment by A-z-z-y** [comment]
Ya know? That's fair. I wouldn't want to learn that stuff either.
