### ISSUE TITLE
Ergo hash rate regression/weird hash rate

### ISSUE THREAD

**Issue by jbright2** [doktor83/SRBMiner-Multi#49]
This is similar to issue #41 I opened a while back.
With SRBMiner 0.7.7 in linux (hiveos), an R9 390 plus the R9 380 with less aggressive overclocks than before would net me:
R9 390 - 50 mh/s
R9 380 - 39 mh/s

On windows:
R9 390 - Fluctuates between 50 to 70 mh/s, averages out at 60
R9 380 - 40 mh/s

lolminer for control, linux (hiveos):
R9 390 - 53 mh/s
R9 380 - 43-44 mh/s

SRBMiner settings on both windows and linux:
--disable-cpu
--gpu-id 0!1
--gpu-boost 0!5
--gpu-auto-tune 1

*worth noting, during auto tune R9 390 hash rate goes very high, ~90 mh/s but settles lower once auto tune is complete

**Comment by doktor83** [comment]
I dont have any of these cards so im doing programming for them totally blindly.

in #41 you wrote you get _~43 in 0.7.3_ with r9 380.
_in 0.7.7 you get 39_

I guess in latest version you get even less, or ?

Why not use 0.7.3 then ?

**Comment by jbright2** [comment]
for the R9 380,  i have underclocked the card since then, so my hash rate dropped to 40 in windows (with SRBMiner 0.7.7).
i then added the R9 390 and got that 50-70 but averages, or settles at 60.

i then switched to hiveos, where the R9 390 hash rate settled at 50 mh/s and the 380 to 39.
i tried lolminer just for control and noticed that hash rates were higher...

i was thinking that it might just be a bug in your miner.

**Comment by doktor83** [comment]
Driver version on Hiveos isn't same as what you use on windows - probably. Also guess oc settings are not same as in windows.
It's not a bug it's just that it runs on a different OS, different driver.. behaves differently.

**Comment by jbright2** [comment]
Driver version in windows is 21.4.1, in hiveos it is at 20.40.
underclock was done through vbios flash, not software.

I see, I just assumed it was a bug or something because I usually get consistently higher hash rate in linux and with your miner vs others. Thanks.
