### ISSUE TITLE
RX 550 - No Binary Found

### ISSUE THREAD

**Issue by jorgehussni** [doktor83/SRBMiner-Multi#50]
Hello guys!

I am running a little test with a Radeon Rx580 and Rx550 but i got this error on SRB Miner:

![image](https://user-images.githubusercontent.com/24920053/127886411-989baa7f-be9f-4dde-b06d-df2b949cc3bc.png)

**Comment by doktor83** [comment]
try latest version maybe? not 0.7.1 ?
