### ISSUE TITLE
RX 570 DEVFEE POOL/S NOT REACHABLE

### ISSUE THREAD

**Issue by coffeerage** [doktor83/SRBMiner-Multi#51]
![Untitled](https://user-images.githubusercontent.com/85581270/128148925-92a55145-6bce-4a3f-814c-29a5191bd518.jpg)
THIS ERROR AFTER RESTART MY PC, PLEASE HELP ME

**Comment by doktor83** [comment]
im sure its fixed now? probably was a short outage of the devfee pool.

**Comment by kharisfauzan** [comment]
![Untitled](https://user-images.githubusercontent.com/75495106/146921798-2783d684-17bf-4eb7-8be2-3b3c99c445d8.png)
