### ISSUE TITLE
11 gpu error

### ISSUE THREAD

**Issue by petrovsky34** [doktor83/SRBMiner-Multi#53]
![27B7EDE7-A786-4F92-AA67-DF8919DE0A0E](https://user-images.githubusercontent.com/39003568/129377294-e899a20d-54f9-4073-8d67-0a038f0fba80.png)

**Comment by doktor83** [comment]
check in console if that gpu is reporting values normally. Hiveos might read miner API wrong, that's why you get that.

**Comment by petrovsky34** [comment]
Ok
