### ISSUE TITLE
Nanopool not working

### ISSUE THREAD

**Issue by denzilferreira** [doktor83/SRBMiner-Multi#56]
Unable to connect to nanopool using SRBMiner 0.8.0

> Reconnecting to ergo-eu1.nanopool.org:11111 in 3 seconds [autolykos2]
> Pool not responding - probably network error [autolykos2]

All works with nanominer, not sure what is wrong.

**Comment by doktor83** [comment]
Probably was a temporary issue with nanopool cause it is working, i just checked now.

**Comment by denzilferreira** [comment]
I can confirm, this was a router issue, not SRBMiner 🤦🏻‍♂️
