### ISSUE TITLE
[yescrypt] Nonce parsing error 

### ISSUE THREAD

**Issue by YetAnotherRussian** [doktor83/SRBMiner-Multi#58]
Algo: yescrypt
Version: 7.9 / 8.0 tested (others untested)
Pool to reproduce: http://p2p-spb.xyz:9554/static/ (web interface), stratum subscr url "p2p-spb.xyz:9554"
Platform: Windows

Result:
![srb](https://user-images.githubusercontent.com/4670472/131832093-87fe45a4-79c4-4643-a2f7-5770afb8c266.png)

Expectation (cpuminer-opt):
![cpo](https://user-images.githubusercontent.com/4670472/131832414-72fe9d12-c71b-4030-b508-eb314efacea4.png)

**Comment by doktor83** [comment]
Yeah cause its a p2p pool, i didn't spend time on adjusting my current stratum parser to it. Might have a look though.
