### ISSUE TITLE
Does not work on 16.04 LTS due to GLIBC version 2.23

### ISSUE THREAD

**Issue by biospb** [doktor83/SRBMiner-Multi#6]
./SRBMiner-MULTI: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by ./SRBMiner-MULTI)

./SRBMiner-MULTI: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.26' not found (required by ./SRBMiner-MULTI)

**Comment by doktor83** [comment]
I know, my whole dev setup is on Ubuntu 18.04 and libc 2.27.
Upgrading your kernel would solve the issue.
I would need to install 16.04 and set up everything from scratch, which would take a lot of time, and maybe at the end i even couldn't make it work.

**Comment by doktor83** [comment]
From version 0.3.9 compiled with libc 2.23 so it should work on Ubuntu 16.04
