### ISSUE TITLE
Preload causes a GPU dead error

### ISSUE THREAD

**Issue by Axze-rgb** [doktor83/SRBMiner-Multi#68]
Hello, I am having an amd R9 Radeon 8 Go, this is the bat file content (Windows 10)

`SRBMiner-MULTI.exe --disable-cpu --algorithm autolykos2 --gpu-auto-tune 2 --pool pool.eu.woolypooly.com:3100 --wallet wallet_address
`

That works, however, when adding the option --gpu-autolykos2-preload 1, this generates a GPU dead error. 

Is my GPU simply too old? 

Thanks

**Comment by doktor83** [comment]
Nope, try without --gpu-auto-tune 2 it should work.

**Comment by Axze-rgb** [comment]
That worked, thanks!

**Comment by Axze-rgb** [comment]
I am reopening because after a night of mining I am experiencing crashes again. But no GPU dead error, the miner just stops. Should I open a new issue?

**Comment by doktor83** [comment]
I think your rig just crashed on block 614400 that was a change from epoch0 to epoch1 in Ergo.

**Comment by Axze-rgb** [comment]
Oh yes I just read about it now, indeed, since no more crash.
