### ISSUE TITLE
Does SRBMiner support Solo Mining?

### ISSUE THREAD

**Issue by imrecsoka** [doktor83/SRBMiner-Multi#7]
HI,

I have tried to look at the readme file.
I am not sure , but i would like to know:
Does SRBMiner support Solo Mining?

Thanks

**Comment by doktor83** [comment]
No, i only do pool/stratum implementations

**Comment by imrecsoka** [comment]
Such a pity.

Would you consider solo ?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
