### ISSUE TITLE
When dual-mining ETH+ZIL, hashrate of ETH not reported to pool

### ISSUE THREAD

**Issue by mailman451** [doktor83/SRBMiner-Multi#70]
When looking at the reported hashrate on the pool (ezil.me) the hasrate is 0 except for some spikes when ZIL is mined, so I presume the second non-ZIL algorithm isn't reporting it's hashrate.

**Comment by doktor83** [comment]
> When looking at the reported hashrate on the pool (ezil.me) the hasrate is 0 except for some spikes when ZIL is mined, so I presume the second non-ZIL algorithm isn't reporting it's hashrate.

ZIL is reported because it is mined. The other algorithm is reported on the pool where you mine it. Ethash that isn't mined on ezil.me won't be reported there, cause ... it is not mined there?

**Comment by mailman451** [comment]
Sorry, I was a bit sketchy. I didn't point out that I also mine ETH on ezil.me.

**Comment by doktor83** [comment]
If you want to mine both zil & eth on ezil.me why not just use :

**SRBMiner-MULTI.exe --disable-cpu --algorithm ethash --pool eu.ezil.me:5555 --wallet eth-wallet.zil-wallet**

**Comment by mailman451** [comment]
Yes, this is the way I'm doing it right now.

But I'm also dual-mining ZIL with other algorithms on different pools and there the hashrate is reported correctly for both algorithms to each pool.

And as I have basically used the same commandline and just changed the non-ZIL part I was just wondering why it's not working with ZIL/ETH on the same pool.

Maybe the problem lies with ezil.me or the way hashrate is reported to pools, I don't know. It's definitenly not a big problem, it's just something that catched my eye.
