### ISSUE TITLE
Error -6 when creating CommandQueue - Linux and HD7970

### ISSUE THREAD

**Issue by Gortef** [doktor83/SRBMiner-Multi#75]
I assumed that HD7970 is often recognized as R9 280, so I thought that SRB would be able to use it since 280 is on the supported GPU  list. But is that not the case?

I am trying to mine Vertcoin with an mmpOS rig that has R9 390 and HD7970, but even after the most recent miner update (that says to have fixed some gpu detections) this error in question still appears with 7970.

For comparison, lolminer uses the HD7970 nicely with Ergo, so the rig itself should be good.

**Comment by doktor83** [comment]
I don't have this card so i can't debug. Sorry.
