### ISSUE TITLE
the computer is hanging.

### ISSUE THREAD

**Issue by BuxarNET** [doktor83/SRBMiner-Multi#76]
I'm trying the miner on 2 platforms running Linux. On one rig with 4 AMD RX570-580 cards, on the second a regular computer with one AMD RX570-580 card. After starting, it works for no more than 5 minutes and everything freezes, it is not possible to press anything on the screen. I use the standard config for mining ETH. Tell me what to do. NBMiner works perfectly on these platforms.

**Comment by doktor83** [comment]
what have you tried to solve this issue? tried changing some OC, or setting --gpu-intensity, or anything beside just running the miner with default parameters?
