### ISSUE TITLE
feature request -- yescryptr16 AMD GPU support

### ISSUE THREAD

**Issue by JacobHin2** [doktor83/SRBMiner-Multi#77]
### Just wanna ask about AMD GPU support for the yescryptr16 algo.

I'm trying to mine a new coin called Qogecoin and it can be mined on CPUs and GPUs however atm there is only an experimental NVIDIA miner meaning many people in the Qogecoin server need a way to GPU mine QOGE on their GPUs

Thanks

**Comment by doktor83** [comment]
its not going to happen, sorry

**Comment by JacobHin2** [comment]
alright
