### ISSUE TITLE
Miner uses only one NUMA node 

### ISSUE THREAD

**Issue by cwlnet** [doktor83/SRBMiner-Multi#78]
Hello

Running on double EPYC 7H12 (each 64 cores):
`SRBMiner-MULTI.exe --algorithm ghostrider --pool stratum+tcps://stratum-ru.rplant.xyz:17056 --wallet *** --password *** --worker 2x7H12_x256 --cpu-threads 256 --disable-gpu`
miner uses only 1 NUMA node (out of 4), thus CPU usage is 25% and hashrate is ~ 5000 H/s.

Is it something missing in the command line or a miner issue?

**Comment by doktor83** [comment]
try without setting the threads number or set it to 0 (--cpu-threads 0)
