### ISSUE TITLE
Invalid solution version rejects VerusCoin

### ISSUE THREAD

**Issue by hellcatz** [doktor83/SRBMiner-Multi#79]
VerusCoin network upgrade at block 1796400 changed the solution version number to 0x06.
VerusCoin pools also provide a "partial solution" field in the mining.notify params.
This should be used to fill the solutions bytes before passing to the hashing algo.

Example partial solution provided in mining.notify params.
06000000000000007ed9c66df6c695b70865a2cbe7b88fa1aac8394a1423952e7833ac9fef7ae6e8438d71941968c7eb6d7d4b7355dc7dfa8b35184bafc7fc7626e332b48eea19e2

**Comment by MishMoshh** [comment]
Hello

I am using SRBMiner-Multi 0.8.4 to ine verus

I am struggling to understand where I can change this parameter. Any suggestions on the file name/ location that needs to be editor. 

Thanks,

**Comment by doktor83** [comment]
@hellcatz 
Yes, i see this error on your and official pool, but not on Zerg for example. Interesting.
Im gonna fix it, thanks for letting me know.

**Comment by Quake4** [comment]
![image](https://user-images.githubusercontent.com/29517243/144001626-4556bc35-afc1-4ee6-8bc1-492c10f87caa.png)

**Comment by iceMongus** [comment]
any news for the latest 0.8.5 update?

**Comment by Ondalf** [comment]
![unknown](https://user-images.githubusercontent.com/7473344/144052462-f27285fc-3b2e-48f8-bb9e-846aa2439951.png)

Just parse the first byte after job clear, and you're done, as seen here: https://github.com/monkins1010/ccminer/blob/Verus2.2/equi/equi-stratum.cpp#L142
Makes it futureproof as well...

**Comment by iceMongus** [comment]
dev any soon release about this VRSC problem ??

**Comment by doktor83** [comment]
soon

**Comment by doktor83** [comment]
Fixed in 0.8.5

**Comment by DCMiner-80** [comment]
Thank you doktor83 everything is working as it should. 👍
