### ISSUE TITLE
How can I install this on headless ubuntu server?  Thanks

### ISSUE THREAD

**Issue by daddydaycare** [doktor83/SRBMiner-Multi#81]

**Comment by doktor83** [comment]
use wget to download here from git, unpack and set up your configuration. that should be all.

**Comment by daddydaycare** [comment]
Would really appreciate it if you could write it out. I have been trying a long time to be able to do it , searching and failing, you would think it easier to pick it up, but people just take for granted I guess and don't actually write these things out.  Maybe even put it on the main section?   Thanks again for your work. Cheers
