### ISSUE TITLE
How should Chinese miners use the software

### ISSUE THREAD

**Issue by 3600cpuminer** [doktor83/SRBMiner-Multi#82]
Recently, the firewall in mainland China has been updated, and the mining software developed by you has detected that the pumping pool cannot be connected.Automatically shut down, do not allow use.Well, can we change the pumping location or I can pay to use your mining program.

**Comment by doktor83** [comment]
Can you use a VPN?

**Comment by 3600cpuminer** [comment]
I'm currently using a port forwarding link to mine pools. If each computer uses a separate VPN, that would be too much trouble because I have 15 CPU miners and more to come

**Comment by 3600cpuminer** [comment]
> 你可以使用VPN吗？

I'm currently using a port forwarding link to mine pools. If each computer uses a separate VPN, that would be too much trouble because I have 15 CPU miners and more to come

**Comment by doktor83** [comment]
Usually a VPN connection is created from the main router that is connected to the world, so all the machines from LAN go out through that connection. 
Also i can add devfee pools you can connect to from China - that should also solve the issue, tell me which algorithm/s you have issue with, and also give me links to pools you can connect to, so i can add them.

**Comment by 3600cpuminer** [comment]
> 
I'm using the Verushash algorithm,China's firewall blocks all pool domain names (including small pools with only a few hundred KHS of computing power), but not ipv4 addresses. You can try changing the pumping address to ipv4 address instead of the pool domain name

**Comment by doktor83** [comment]
you could try redirecting with hosts file.
verushash.eu.mine.zergpool.com 79.137.70.172

**Comment by doktor83** [comment]
> > 
> 
> I'm using the Verushash algorithm,China's firewall blocks all pool domain names (including small pools with only a few hundred KHS of computing power), but not ipv4 addresses. You can try changing the pumping address to ipv4 address instead of the pool domain name

Are ip addresses of external DNS services blocked ?

**Comment by sidwellscala** [comment]
The most applicable way to bypass blockage by a firewall is a use of a socks5 proxy. NBMiner, Gminer, CPUMiner forks including that of ghost rider, all have --proxy or -x  argument that that accepts a socks5 proxy that is in user:pass@host:port format. I am adding to what 2600cpuminer has been trying to accomplish. So an implementation of a socks5 proxy would be highly useful.

A practical use case would be: create a socks5 tunnel via ssh by executing ssh ubuntu@1.2.3.4 -o StrictHostKeyChecking=no -D 1338 -f -C -q -N -i key.pem -p 443

and then Socksify srb miner by executing this: ./SrbMiner --disable-gpu --algorithm ghostrider --pool rtm.suprnova.cc:6273 --wallet Username.BlockMuncher --password x --proxy 127.0.0.1:1338

If you try to use srb miner with Proxychains or graftcp, it will yell at you with "naughty" phrase

**Comment by wahaobi** [comment]
EPIC can't be connected, so I will change the IP as well.

> 您可以尝试使用主机文件重定向。 verushash.eu.mine.zergpool.com 79.137.70.172

EPIC can't be connected, so I will change the IP as well.

**Comment by doktor83** [comment]
> EPIC can't be connected, so I will change the IP as well.
> 
> > 您可以尝试使用主机文件重定向。 verushash.eu.mine.zergpool.com 79.137.70.172
> 
> EPIC can't be connected, so I will change the IP as well.

Both hostnames and ip addresses are added for devfee pool on Epic (51pool, icemining). so if you are mining on any of those then they should be connectable. Of course if you are going through a proxy then it's a different story.

**Comment by nathanfleight** [comment]
> 

Can you please consider implementing socks5 support just like NBMiner and Gminer did?

**Comment by doktor83** [comment]
looks like i'll have to consider it after all

**Comment by nathanfleight** [comment]
Thanks bro,we are all looking forward to it, it would be really helpful

**Comment by doktor83** [comment]
Good news, looks like i got it working. Need a lot of testing but if all goes will i will release a new version in a few days.

**Comment by doktor83** [comment]
added socks5 proxy support in version 0.8.8
