### ISSUE TITLE
Please. Can you put the commands on how to pull this to a headless server on your main page?

### ISSUE THREAD

**Issue by daddydaycare** [doktor83/SRBMiner-Multi#83]
I have been trying to teach myself how to do this on headless servers, but I haven't been able to. Easy enough with a desktop. Can you put the steps below where you list the versions?  Be so appreciated. Thanks

**Comment by doktor83** [comment]
wget https://github.com/doktor83/SRBMiner-Multi/releases/download/0.8.5/SRBMiner-Multi-0-8-5-Linux.tar.xz
tar -xf SRBMiner-Multi-0-8-5-Linux.tar.xz
edit any of the examples .sh

should work

**Comment by daddydaycare** [comment]
Thank you very, very much!
