### ISSUE TITLE
Parse error, params has wrong number of fields [ghostrider]

### ISSUE THREAD

**Issue by Iweirdo** [doktor83/SRBMiner-Multi#86]
Guys, hello,
I tried 
SRBMiner-MULTI.exe --disable-gpu --algorithm ghostrider --pool flux-eu.coinblockers.com:4446 --wallet t1eseJzCgYfu2kDdRGaitx2rDFgR65eV3Gp
but got error:Parse error, params has wrong number of fields [ghostrider]
could anyone help, many thanks.

**Comment by doktor83** [comment]
yeah, use a different pool
