### ISSUE TITLE
Mining activity not appearing on WoolyPooly

### ISSUE THREAD

**Issue by Axze-rgb** [doktor83/SRBMiner-Multi#88]
Hello, I updated this morning from 0.8.2 to 0.8.7. I am using the exact same config. It definitely appears the software is mining, but I don't see it on WoolyPooly. This has been going on for hours so it's not a slight delay of few minutes that can happen on WoolyPooly.  Here is the bat file content (I just redacted the address) 

`SRBMiner-MULTI.exe --disable-cpu --algorithm autolykos2 --gpu-autolykos2-preload 1 --pool pool.eu.woolypooly.com:3100 --wallet`

Is it something I should see with WoolyPooly? 
thank you 

EDIT: okay, actually the windows powershell tells me  

`Pool unexpectedly closed the connection autolykos2`

EDIT2: reverting to 0.8.2 my mining activity shows up on WoolyPooly, no error either in the Powershell.

**Comment by doktor83** [comment]
SRBMiner-MULTI.exe --disable-cpu --algorithm autolykos2 --pool pool.eu.woolypooly.com:3100 --wallet 9gj5rYtg1sGwdvoXGJswrSfPBXiXJgmyjZVEQ9p5fvZrCAfu6zT**.my_worker_name** --gpu-autolykos2-preload 1

Works..

**Comment by Axze-rgb** [comment]
Indeed, thanks

**Comment by Axze-rgb** [comment]
Hello, reopening the issue because it manifests again.

**Comment by doktor83** [comment]
It's not a miner issue, you need to set the correct format for wooly and that is wallet.worker_name. Maybe write to wooly support instead if you say you set it CORRECTLY in miner, but its not showing up on pool?

**Comment by Axze-rgb** [comment]
yes I will do that, thanks
