### ISSUE TITLE
For windows bat file 

### ISSUE THREAD

**Issue by faikuluturk** [doktor83/SRBMiner-Multi#91]
Hello this is not an isue but i have 15 rig cpu only i cant mark every rig as specific worker name can u help me on that all is named default on icemining web site . i tried (--worker) doesnt work .

![image](https://user-images.githubusercontent.com/86348797/149513159-42bab4b0-8044-441f-85d3-b7f5878e62a8.png)

**Comment by doktor83** [comment]
Pool expects you to use format **--wallet user.workername**
