### ISSUE TITLE
One minute delay at start

### ISSUE THREAD

**Issue by Quake4** [doktor83/SRBMiner-Multi#93]
![image](https://user-images.githubusercontent.com/29517243/152294586-2dd0a359-6fe9-4617-9747-c48100cd0755.png)
![image](https://user-images.githubusercontent.com/29517243/152297568-88a588f1-6871-4ac4-a561-f0e18a685e83.png)

**Comment by doktor83** [comment]
Miner at startup queries devfee pool hosts and some DNS stuff. 
If those hosts are 'problematic' that might slow down the startup process.
Luckily its not always and user doesn't start miner every 10 minutes.

**Comment by Quake4** [comment]
After such a delay, the incorrect speed is given by the API taking into account this minute.
